// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec account_deactivation.yaml: do not edit.
export module loom.cs.account_deactivation;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/account/deactivate: Deactivate a user's account.
struct deactivate_account {
  struct body_t {
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>().member<"rest">(knot::rest); }
    };
    std::optional<authentication_data_t> auth;
    std::optional<std::string> id_server;
    std::optional<bool> erase;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    struct id_server_unbind_result_values {
      struct success {
        static constexpr std::string_view json_value = "success";
        friend constexpr bool operator==(success, success) = default;
      };
      struct no_support {
        static constexpr std::string_view json_value = "no-support";
        friend constexpr bool operator==(no_support, no_support) = default;
      };
    };
    using id_server_unbind_result_t = splice::variant<id_server_unbind_result_values::success, id_server_unbind_result_values::no_support, std::string>;
    id_server_unbind_result_t id_server_unbind_result;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/deactivate";
    return {method::post{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
