// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec account-data.yaml: do not edit.
export module loom.cs.account_data;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// PUT /_matrix/client/v3/user/{userId}/account_data/{type}: Set some account data for the user.
struct set_account_data {
  std::string user_id;
  std::string type;
  knot::raw body;
  using response = knot::raw;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/account_data/" + percent_encoded(detail::text(type));
    return {method::put{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/client/v3/user/{userId}/account_data/{type}: Get some account data for the user.
struct get_account_data {
  std::string user_id;
  std::string type;
  using response = knot::raw;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/account_data/" + percent_encoded(detail::text(type));
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// PUT /_matrix/client/v3/user/{userId}/rooms/{roomId}/account_data/{type}: Set some account data for the user that is specific to a room.
struct set_account_data_per_room {
  std::string user_id;
  std::string room_id;
  std::string type;
  knot::raw body;
  using response = knot::raw;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/rooms/" + percent_encoded(detail::text(room_id)) + "/account_data/" + percent_encoded(detail::text(type));
    return {method::put{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/client/v3/user/{userId}/rooms/{roomId}/account_data/{type}: Get some account data for the user that is specific to a room.
struct get_account_data_per_room {
  std::string user_id;
  std::string room_id;
  std::string type;
  using response = knot::raw;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/rooms/" + percent_encoded(detail::text(room_id)) + "/account_data/" + percent_encoded(detail::text(type));
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
