// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec administrative_contact.yaml: do not edit.
export module loom.cs.administrative_contact;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/account/3pid: Gets a list of a user's third-party identifiers.
struct get_account3_pi_ds {
  struct response_t {
    struct third_party_identifier_t {
      struct medium_values {
        struct email {
          static constexpr std::string_view json_value = "email";
          friend constexpr bool operator==(email, email) = default;
        };
        struct msisdn {
          static constexpr std::string_view json_value = "msisdn";
          friend constexpr bool operator==(msisdn, msisdn) = default;
        };
      };
      using medium_t = spl::variant<medium_values::email, medium_values::msisdn, std::string>;
      medium_t medium;
      std::string address;
      std::int64_t validated_at;
      std::int64_t added_at;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<third_party_identifier_t>) { return knot::schema<third_party_identifier_t>().member<"rest">(knot::rest); }
    };
    std::optional<std::vector<third_party_identifier_t>> threepids;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid";
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/account/3pid: Adds contact information to the user's account. (deprecated)
struct post3_pi_ds {
  struct body_t {
    struct three_pid_credentials_t {
      std::string client_secret;
      std::string id_server;
      std::string id_access_token;
      std::string sid;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<three_pid_credentials_t>) { return knot::schema<three_pid_credentials_t>().member<"rest">(knot::rest); }
    };
    three_pid_credentials_t three_pid_creds;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    std::optional<std::string> submit_url;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid";
    return {method::post{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/account/3pid/add: Adds contact information to the user's account.
struct add3_pid {
  struct body_t {
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>().member<"rest">(knot::rest); }
    };
    std::optional<authentication_data_t> auth;
    std::string client_secret;
    std::string sid;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = knot::raw;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/add";
    return {method::post{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/account/3pid/bind: Binds a 3PID to the user's account through an Identity Service.
struct bind3_pid {
  struct body_t {
    std::string client_secret;
    std::string id_server;
    std::string id_access_token;
    std::string sid;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = knot::raw;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/bind";
    return {method::post{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/account/3pid/delete: Deletes a third-party identifier from the user's account
struct delete3pid_from_account {
  struct body_t {
    struct medium_values {
      struct email {
        static constexpr std::string_view json_value = "email";
        friend constexpr bool operator==(email, email) = default;
      };
      struct msisdn {
        static constexpr std::string_view json_value = "msisdn";
        friend constexpr bool operator==(msisdn, msisdn) = default;
      };
    };
    using medium_t = spl::variant<medium_values::email, medium_values::msisdn, std::string>;
    std::optional<std::string> id_server;
    medium_t medium;
    std::string address;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    struct id_server_unbind_result_values {
      struct no_support {
        static constexpr std::string_view json_value = "no-support";
        friend constexpr bool operator==(no_support, no_support) = default;
      };
      struct success {
        static constexpr std::string_view json_value = "success";
        friend constexpr bool operator==(success, success) = default;
      };
    };
    using id_server_unbind_result_t = spl::variant<id_server_unbind_result_values::no_support, id_server_unbind_result_values::success, std::string>;
    id_server_unbind_result_t id_server_unbind_result;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/delete";
    return {method::post{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/account/3pid/unbind: Removes a user's third-party identifier from an identity server.
struct unbind3pid_from_account {
  struct body_t {
    struct medium_values {
      struct email {
        static constexpr std::string_view json_value = "email";
        friend constexpr bool operator==(email, email) = default;
      };
      struct msisdn {
        static constexpr std::string_view json_value = "msisdn";
        friend constexpr bool operator==(msisdn, msisdn) = default;
      };
    };
    using medium_t = spl::variant<medium_values::email, medium_values::msisdn, std::string>;
    std::optional<std::string> id_server;
    medium_t medium;
    std::string address;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    struct id_server_unbind_result_values {
      struct no_support {
        static constexpr std::string_view json_value = "no-support";
        friend constexpr bool operator==(no_support, no_support) = default;
      };
      struct success {
        static constexpr std::string_view json_value = "success";
        friend constexpr bool operator==(success, success) = default;
      };
    };
    using id_server_unbind_result_t = spl::variant<id_server_unbind_result_values::no_support, id_server_unbind_result_values::success, std::string>;
    id_server_unbind_result_t id_server_unbind_result;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/unbind";
    return {method::post{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/account/3pid/email/requestToken: Begins the validation process for an email address for association with the user's account.
struct request_token_to3_pid_email {
  def::request_email_validation_t body;
  using response = def::request_token_response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/email/requestToken";
    return {method::post{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/account/3pid/msisdn/requestToken: Begins the validation process for a phone number for association with the user's account.
struct request_token_to3_pidmsisdn {
  def::request_msisdn_validation_t body;
  using response = def::request_token_response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/msisdn/requestToken";
    return {method::post{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
