// Generated by tools/generate.py from matrix-spec administrative_contact.yaml: do not edit.
export module loom.cs.administrative_contact;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/account/3pid: Gets a list of a user's third-party identifiers.
struct get_account3_pi_ds {
  struct response_t {
    struct third_party_identifier_t {
      struct medium_values {
        struct email {
          static constexpr std::string_view json_value = "email";
          friend constexpr bool operator==(email, email) = default;
        };
        struct msisdn {
          static constexpr std::string_view json_value = "msisdn";
          friend constexpr bool operator==(msisdn, msisdn) = default;
        };
      };
      using medium_t = std::variant<medium_values::email, medium_values::msisdn, std::string>;
      medium_t medium;
      std::string address;
      std::int64_t validated_at;
      std::int64_t added_at;
      friend consteval auto json_schema(knot::type<third_party_identifier_t>) { return knot::schema<third_party_identifier_t>(); }
    };
    std::optional<std::vector<third_party_identifier_t>> threepids;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid";
    return {method::get{}, std::move(target), "", true};
  }
};

// POST /_matrix/client/v3/account/3pid: Adds contact information to the user's account. (deprecated)
struct post3_pi_ds {
  struct body_t {
    struct three_pid_credentials_t {
      std::string client_secret;
      std::string id_server;
      std::string id_access_token;
      std::string sid;
      friend consteval auto json_schema(knot::type<three_pid_credentials_t>) { return knot::schema<three_pid_credentials_t>(); }
    };
    three_pid_credentials_t three_pid_creds;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    std::optional<std::string> submit_url;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/account/3pid/add: Adds contact information to the user's account.
struct add3_pid {
  struct body_t {
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>(); }
    };
    std::optional<authentication_data_t> auth;
    std::string client_secret;
    std::string sid;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/add";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/account/3pid/bind: Binds a 3PID to the user's account through an Identity Service.
struct bind3_pid {
  struct body_t {
    std::string client_secret;
    std::string id_server;
    std::string id_access_token;
    std::string sid;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/bind";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/account/3pid/delete: Deletes a third-party identifier from the user's account
struct delete3pid_from_account {
  struct body_t {
    struct medium_values {
      struct email {
        static constexpr std::string_view json_value = "email";
        friend constexpr bool operator==(email, email) = default;
      };
      struct msisdn {
        static constexpr std::string_view json_value = "msisdn";
        friend constexpr bool operator==(msisdn, msisdn) = default;
      };
    };
    using medium_t = std::variant<medium_values::email, medium_values::msisdn, std::string>;
    std::optional<std::string> id_server;
    medium_t medium;
    std::string address;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    struct id_server_unbind_result_values {
      struct no_support {
        static constexpr std::string_view json_value = "no-support";
        friend constexpr bool operator==(no_support, no_support) = default;
      };
      struct success {
        static constexpr std::string_view json_value = "success";
        friend constexpr bool operator==(success, success) = default;
      };
    };
    using id_server_unbind_result_t = std::variant<id_server_unbind_result_values::no_support, id_server_unbind_result_values::success, std::string>;
    id_server_unbind_result_t id_server_unbind_result;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/delete";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/account/3pid/unbind: Removes a user's third-party identifier from an identity server.
struct unbind3pid_from_account {
  struct body_t {
    struct medium_values {
      struct email {
        static constexpr std::string_view json_value = "email";
        friend constexpr bool operator==(email, email) = default;
      };
      struct msisdn {
        static constexpr std::string_view json_value = "msisdn";
        friend constexpr bool operator==(msisdn, msisdn) = default;
      };
    };
    using medium_t = std::variant<medium_values::email, medium_values::msisdn, std::string>;
    std::optional<std::string> id_server;
    medium_t medium;
    std::string address;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    struct id_server_unbind_result_values {
      struct no_support {
        static constexpr std::string_view json_value = "no-support";
        friend constexpr bool operator==(no_support, no_support) = default;
      };
      struct success {
        static constexpr std::string_view json_value = "success";
        friend constexpr bool operator==(success, success) = default;
      };
    };
    using id_server_unbind_result_t = std::variant<id_server_unbind_result_values::no_support, id_server_unbind_result_values::success, std::string>;
    id_server_unbind_result_t id_server_unbind_result;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/unbind";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/account/3pid/email/requestToken: Begins the validation process for an email address for association with the user's account.
struct request_token_to3_pid_email {
  def::request_email_validation_t body;
  using response = def::request_token_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/email/requestToken";
    return {method::post{}, std::move(target), detail::json(body), false};
  }
};

// POST /_matrix/client/v3/account/3pid/msisdn/requestToken: Begins the validation process for a phone number for association with the user's account.
struct request_token_to3_pidmsisdn {
  def::request_msisdn_validation_t body;
  using response = def::request_token_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/3pid/msisdn/requestToken";
    return {method::post{}, std::move(target), detail::json(body), false};
  }
};
}  // namespace loom::cs
