// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec admin.yaml: do not edit.
export module loom.cs.admin;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/admin/whois/{userId}: Gets information about a particular user.
struct get_who_is {
  struct response_t {
    struct device_info_t {
      struct session_info_t {
        struct connection_info_t {
          std::optional<std::string> ip;
          std::optional<std::int64_t> last_seen;
          std::optional<std::string> user_agent;
          knot::value rest;
          friend consteval auto json_schema(knot::type<connection_info_t>) { return knot::schema<connection_info_t>().member<"rest">(knot::rest); }
        };
        std::optional<std::vector<connection_info_t>> connections;
        knot::value rest;
        friend consteval auto json_schema(knot::type<session_info_t>) { return knot::schema<session_info_t>().member<"rest">(knot::rest); }
      };
      std::optional<std::vector<session_info_t>> sessions;
      knot::value rest;
      friend consteval auto json_schema(knot::type<device_info_t>) { return knot::schema<device_info_t>().member<"rest">(knot::rest); }
    };
    std::optional<std::string> user_id;
    std::optional<std::map<std::string, device_info_t>> devices;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client") + "/v3/admin/whois/" + percent_encoded(detail::text(user_id));
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v1/admin/suspend/{userId}: Gets information about the suspended status of a particular user.
struct get_admin_suspend_user {
  struct response_t {
    bool suspended;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client") + "/v1/admin/suspend/" + percent_encoded(detail::text(user_id));
    return {method::get{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v1/admin/suspend/{userId}: Set the suspended status of a particular user.
struct set_admin_suspend_user {
  struct body_t {
    bool suspended;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    bool suspended;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client") + "/v1/admin/suspend/" + percent_encoded(detail::text(user_id));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v1/admin/lock/{userId}: Gets information about the locked status of a particular user.
struct get_admin_lock_user {
  struct response_t {
    bool locked;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client") + "/v1/admin/lock/" + percent_encoded(detail::text(user_id));
    return {method::get{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v1/admin/lock/{userId}: Set the locked status of a particular user.
struct set_admin_lock_user {
  struct body_t {
    bool locked;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    bool locked;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client") + "/v1/admin/lock/" + percent_encoded(detail::text(user_id));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
