// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec appservice_ping.yaml: do not edit.
export module loom.cs.appservice_ping;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v1/appservice/{appserviceId}/ping: Ask the homeserver to ping the application service to ensure the connection works.
struct ping_appservice {
  struct body_t {
    std::optional<std::string> transaction_id;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    std::int64_t duration_ms;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string appservice_id;
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/appservice/" + percent_encoded(detail::text(appservice_id)) + "/ping";
    return {method::post{}, std::move(target), detail::json(body), false};
  }
};
}  // namespace loom::cs
