// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec authed-content-repo.yaml: do not edit.
export module loom.cs.authed_content_repo;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/media/download/{serverName}/{mediaId}: Download content from the content repository.
struct get_content_authed {
  std::string server_name;
  std::string media_id;
  std::optional<std::int64_t> timeout_ms;
  struct response {
    std::string bytes;
  };
  static constexpr bool raw_response = true;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/media/download/" + percent_encoded(detail::text(server_name)) + "/" + percent_encoded(detail::text(media_id));
    if (timeout_ms)
      detail::query(target, "timeout_ms", detail::text((*timeout_ms)));
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v1/media/download/{serverName}/{mediaId}/{fileName}: Download content from the content repository overriding the file name.
struct get_content_override_name_authed {
  std::string server_name;
  std::string media_id;
  std::string file_name;
  std::optional<std::int64_t> timeout_ms;
  struct response {
    std::string bytes;
  };
  static constexpr bool raw_response = true;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/media/download/" + percent_encoded(detail::text(server_name)) + "/" + percent_encoded(detail::text(media_id)) + "/" + percent_encoded(detail::text(file_name));
    if (timeout_ms)
      detail::query(target, "timeout_ms", detail::text((*timeout_ms)));
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v1/media/thumbnail/{serverName}/{mediaId}: Download a thumbnail of content from the content repository
struct get_content_thumbnail_authed {
  struct method_values {
    struct crop {
      static constexpr std::string_view json_value = "crop";
      friend constexpr bool operator==(crop, crop) = default;
    };
    struct scale {
      static constexpr std::string_view json_value = "scale";
      friend constexpr bool operator==(scale, scale) = default;
    };
  };
  using method_t = std::variant<method_values::crop, method_values::scale, std::string>;
  std::string server_name;
  std::string media_id;
  std::int64_t width;
  std::int64_t height;
  std::optional<method_t> method;
  std::optional<std::int64_t> timeout_ms;
  std::optional<bool> animated;
  struct response {
    std::string bytes;
  };
  static constexpr bool raw_response = true;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/media/thumbnail/" + percent_encoded(detail::text(server_name)) + "/" + percent_encoded(detail::text(media_id));
    detail::query(target, "width", detail::text(width));
    detail::query(target, "height", detail::text(height));
    if (method)
      detail::query(target, "method", detail::text((*method)));
    if (timeout_ms)
      detail::query(target, "timeout_ms", detail::text((*timeout_ms)));
    if (animated)
      detail::query(target, "animated", detail::text((*animated)));
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v1/media/preview_url: Get information about a URL for a client
struct get_url_preview_authed {
  struct response_t {
    std::optional<std::int64_t> matrix_image_size;
    std::optional<std::string> og_image;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"matrix_image_size">(knot::key("matrix:image:size")).member<"og_image">(knot::key("og:image")).member<"rest">(knot::rest); }
  };
  std::string url;
  std::optional<std::int64_t> ts;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/media/preview_url";
    detail::query(target, "url", detail::text(url));
    if (ts)
      detail::query(target, "ts", detail::text((*ts)));
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v1/media/config: Get the configuration for the content repository.
struct get_config_authed {
  struct response_t {
    std::optional<std::int64_t> m_upload_size;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"m_upload_size">(knot::key("m.upload.size")).member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/media/config";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
