// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec banning.yaml: do not edit.
export module loom.cs.banning;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/rooms/{roomId}/ban: Ban a user in the room.
struct ban {
  struct body_t {
    std::string user_id;
    std::optional<std::string> reason;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/ban";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/rooms/{roomId}/unban: Unban a user from the room.
struct unban {
  struct body_t {
    std::string user_id;
    std::optional<std::string> reason;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/unban";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
