// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec capabilities.yaml: do not edit.
export module loom.cs.capabilities;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/capabilities: Gets information about the server's capabilities.
struct get_capabilities {
  struct response_t {
    struct capabilities_t {
      struct room_versions_capability_t {
        struct available_value_values {
          struct stable {
            static constexpr std::string_view json_value = "stable";
            friend constexpr bool operator==(stable, stable) = default;
          };
          struct unstable {
            static constexpr std::string_view json_value = "unstable";
            friend constexpr bool operator==(unstable, unstable) = default;
          };
        };
        using available_value_t = std::variant<available_value_values::stable, available_value_values::unstable, std::string>;
        std::string default_;
        std::map<std::string, available_value_t> available;
        friend consteval auto json_schema(knot::type<room_versions_capability_t>) { return knot::schema<room_versions_capability_t>().member<"default_">(knot::key("default")); }
      };
      struct profile_fields_capability_t {
        std::optional<std::vector<std::string>> allowed;
        std::optional<std::vector<std::string>> disallowed;
        bool enabled;
        friend consteval auto json_schema(knot::type<profile_fields_capability_t>) { return knot::schema<profile_fields_capability_t>(); }
      };
      struct account_moderation_capability_t {
        std::optional<bool> suspend;
        std::optional<bool> lock;
        friend consteval auto json_schema(knot::type<account_moderation_capability_t>) { return knot::schema<account_moderation_capability_t>(); }
      };
      std::optional<def::boolean_capability_t> m_change_password;
      std::optional<def::boolean_capability_t> m_forget_forced_upon_leave;
      std::optional<room_versions_capability_t> m_room_versions;
      std::optional<def::boolean_capability_t> m_set_displayname;
      std::optional<def::boolean_capability_t> m_set_avatar_url;
      std::optional<def::boolean_capability_t> m_3pid_changes;
      std::optional<def::boolean_capability_t> m_get_login_token;
      std::optional<profile_fields_capability_t> m_profile_fields;
      std::optional<account_moderation_capability_t> m_account_moderation;
      friend consteval auto json_schema(knot::type<capabilities_t>) { return knot::schema<capabilities_t>().member<"m_change_password">(knot::key("m.change_password")).member<"m_forget_forced_upon_leave">(knot::key("m.forget_forced_upon_leave")).member<"m_room_versions">(knot::key("m.room_versions")).member<"m_set_displayname">(knot::key("m.set_displayname")).member<"m_set_avatar_url">(knot::key("m.set_avatar_url")).member<"m_3pid_changes">(knot::key("m.3pid_changes")).member<"m_get_login_token">(knot::key("m.get_login_token")).member<"m_profile_fields">(knot::key("m.profile_fields")).member<"m_account_moderation">(knot::key("m.account_moderation")); }
    };
    capabilities_t capabilities;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/capabilities";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
