// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec content-repo.yaml: do not edit.
export module loom.cs.content_repo;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/media/v3/upload: Upload some content to the content repository.
struct upload_content {
  struct response_t {
    std::string content_uri;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::optional<std::string> filename;
  std::string body;  // the bytes, as the content type says
  std::string content_type = "application/octet-stream";
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix") + "/media/v3/upload";
    if (filename)
      detail::query(target, "filename", detail::text((*filename)));
    return {method::post{}, std::move(target), true, content_type};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    if (!body.empty()) std::invoke(sink, std::string_view(body));
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// PUT /_matrix/media/v3/upload/{serverName}/{mediaId}: Upload content to an `mxc://` URI that was created earlier.
struct upload_content_to_mxc {
  std::string server_name;
  std::string media_id;
  std::optional<std::string> filename;
  std::string body;  // the bytes, as the content type says
  std::string content_type = "application/octet-stream";
  using response = knot::raw;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix") + "/media/v3/upload/" + percent_encoded(detail::text(server_name)) + "/" + percent_encoded(detail::text(media_id));
    if (filename)
      detail::query(target, "filename", detail::text((*filename)));
    return {method::put{}, std::move(target), true, content_type};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    if (!body.empty()) std::invoke(sink, std::string_view(body));
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/media/v1/create: Create a new `mxc://` URI without uploading the content.
struct create_content {
  struct response_t {
    std::string content_uri;
    std::optional<std::int64_t> unused_expires_at;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix") + "/media/v1/create";
    return {method::post{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    std::invoke(sink, std::string_view("{}"));
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/media/v3/download/{serverName}/{mediaId}: Download content from the content repository. (deprecated)
struct get_content {
  std::string server_name;
  std::string media_id;
  std::optional<bool> allow_remote;
  std::optional<std::int64_t> timeout_ms;
  std::optional<bool> allow_redirect;
  struct response {
    std::string bytes;
  };
  static constexpr bool raw_response = true;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix") + "/media/v3/download/" + percent_encoded(detail::text(server_name)) + "/" + percent_encoded(detail::text(media_id));
    if (allow_remote)
      detail::query(target, "allow_remote", detail::text((*allow_remote)));
    if (timeout_ms)
      detail::query(target, "timeout_ms", detail::text((*timeout_ms)));
    if (allow_redirect)
      detail::query(target, "allow_redirect", detail::text((*allow_redirect)));
    return {method::get{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/media/v3/download/{serverName}/{mediaId}/{fileName}: Download content from the content repository overriding the file name (deprecated)
struct get_content_override_name {
  std::string server_name;
  std::string media_id;
  std::string file_name;
  std::optional<bool> allow_remote;
  std::optional<std::int64_t> timeout_ms;
  std::optional<bool> allow_redirect;
  struct response {
    std::string bytes;
  };
  static constexpr bool raw_response = true;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix") + "/media/v3/download/" + percent_encoded(detail::text(server_name)) + "/" + percent_encoded(detail::text(media_id)) + "/" + percent_encoded(detail::text(file_name));
    if (allow_remote)
      detail::query(target, "allow_remote", detail::text((*allow_remote)));
    if (timeout_ms)
      detail::query(target, "timeout_ms", detail::text((*timeout_ms)));
    if (allow_redirect)
      detail::query(target, "allow_redirect", detail::text((*allow_redirect)));
    return {method::get{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/media/v3/thumbnail/{serverName}/{mediaId}: Download a thumbnail of content from the content repository (deprecated)
struct get_content_thumbnail {
  struct method_values {
    struct crop {
      static constexpr std::string_view json_value = "crop";
      friend constexpr bool operator==(crop, crop) = default;
    };
    struct scale {
      static constexpr std::string_view json_value = "scale";
      friend constexpr bool operator==(scale, scale) = default;
    };
  };
  using method_t = spl::variant<method_values::crop, method_values::scale, std::string>;
  std::string server_name;
  std::string media_id;
  std::int64_t width;
  std::int64_t height;
  std::optional<method_t> method;
  std::optional<bool> allow_remote;
  std::optional<std::int64_t> timeout_ms;
  std::optional<bool> allow_redirect;
  std::optional<bool> animated;
  struct response {
    std::string bytes;
  };
  static constexpr bool raw_response = true;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix") + "/media/v3/thumbnail/" + percent_encoded(detail::text(server_name)) + "/" + percent_encoded(detail::text(media_id));
    detail::query(target, "width", detail::text(width));
    detail::query(target, "height", detail::text(height));
    if (method)
      detail::query(target, "method", detail::text((*method)));
    if (allow_remote)
      detail::query(target, "allow_remote", detail::text((*allow_remote)));
    if (timeout_ms)
      detail::query(target, "timeout_ms", detail::text((*timeout_ms)));
    if (allow_redirect)
      detail::query(target, "allow_redirect", detail::text((*allow_redirect)));
    if (animated)
      detail::query(target, "animated", detail::text((*animated)));
    return {method::get{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/media/v3/preview_url: Get information about a URL for a client (deprecated)
struct get_url_preview {
  struct response_t {
    std::optional<std::int64_t> matrix_image_size;
    std::optional<std::string> og_image;
    std::optional<std::string> og_site_name;
    std::optional<std::string> og_title;
    std::optional<std::string> og_description;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"matrix_image_size">(knot::key("matrix:image:size")).member<"og_image">(knot::key("og:image")).member<"og_site_name">(knot::key("og:site_name")).member<"og_title">(knot::key("og:title")).member<"og_description">(knot::key("og:description")).member<"rest">(knot::rest); }
  };
  std::string url;
  std::optional<std::int64_t> ts;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix") + "/media/v3/preview_url";
    detail::query(target, "url", detail::text(url));
    if (ts)
      detail::query(target, "ts", detail::text((*ts)));
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/media/v3/config: Get the configuration for the content repository. (deprecated)
struct get_config {
  struct response_t {
    std::optional<std::int64_t> m_upload_size;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"m_upload_size">(knot::key("m.upload.size")).member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix") + "/media/v3/config";
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
