// Generated by tools/generate.py from matrix-spec create_room.yaml: do not edit.
export module loom.cs.create_room;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/createRoom: Create a new room
struct create_room {
  struct body_t {
    struct visibility_values {
      struct public_ {
        static constexpr std::string_view json_value = "public";
        friend constexpr bool operator==(public_, public_) = default;
      };
      struct private_ {
        static constexpr std::string_view json_value = "private";
        friend constexpr bool operator==(private_, private_) = default;
      };
    };
    using visibility_t = std::variant<visibility_values::public_, visibility_values::private_, std::string>;
    struct state_event_t {
      std::string type;
      std::optional<std::string> state_key;
      knot::value content;
      friend consteval auto json_schema(knot::type<state_event_t>) { return knot::schema<state_event_t>(); }
    };
    struct preset_values {
      struct private_chat {
        static constexpr std::string_view json_value = "private_chat";
        friend constexpr bool operator==(private_chat, private_chat) = default;
      };
      struct public_chat {
        static constexpr std::string_view json_value = "public_chat";
        friend constexpr bool operator==(public_chat, public_chat) = default;
      };
      struct trusted_private_chat {
        static constexpr std::string_view json_value = "trusted_private_chat";
        friend constexpr bool operator==(trusted_private_chat, trusted_private_chat) = default;
      };
    };
    using preset_t = std::variant<preset_values::private_chat, preset_values::public_chat, preset_values::trusted_private_chat, std::string>;
    std::optional<visibility_t> visibility;
    std::optional<std::string> room_alias_name;
    std::optional<std::string> name;
    std::optional<std::string> topic;
    std::optional<std::vector<std::string>> invite;
    std::optional<std::vector<def::invite3pid_t>> invite_3pid;
    std::optional<std::string> room_version;
    std::optional<knot::value> creation_content;
    std::optional<std::vector<state_event_t>> initial_state;
    std::optional<preset_t> preset;
    std::optional<bool> is_direct;
    std::optional<knot::value> power_level_content_override;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    std::string room_id;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/createRoom";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
