// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec cross_signing.yaml: do not edit.
export module loom.cs.cross_signing;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/keys/device_signing/upload: Upload cross-signing keys.
struct upload_cross_signing_keys {
  struct body_t {
    struct cross_signing_key_t {
      struct usage_item_values {
        struct master {
          static constexpr std::string_view json_value = "master";
          friend constexpr bool operator==(master, master) = default;
        };
        struct self_signing {
          static constexpr std::string_view json_value = "self_signing";
          friend constexpr bool operator==(self_signing, self_signing) = default;
        };
        struct user_signing {
          static constexpr std::string_view json_value = "user_signing";
          friend constexpr bool operator==(user_signing, user_signing) = default;
        };
      };
      using usage_item_t = std::variant<usage_item_values::master, usage_item_values::self_signing, usage_item_values::user_signing, std::string>;
      std::string user_id;
      std::vector<usage_item_t> usage;
      std::map<std::string, std::string> keys;
      std::optional<knot::value> signatures;
      friend consteval auto json_schema(knot::type<cross_signing_key_t>) { return knot::schema<cross_signing_key_t>(); }
    };
    struct cross_signing_key_2_t {
      struct usage_item_values {
        struct master {
          static constexpr std::string_view json_value = "master";
          friend constexpr bool operator==(master, master) = default;
        };
        struct self_signing {
          static constexpr std::string_view json_value = "self_signing";
          friend constexpr bool operator==(self_signing, self_signing) = default;
        };
        struct user_signing {
          static constexpr std::string_view json_value = "user_signing";
          friend constexpr bool operator==(user_signing, user_signing) = default;
        };
      };
      using usage_item_t = std::variant<usage_item_values::master, usage_item_values::self_signing, usage_item_values::user_signing, std::string>;
      std::string user_id;
      std::vector<usage_item_t> usage;
      std::map<std::string, std::string> keys;
      std::optional<knot::value> signatures;
      friend consteval auto json_schema(knot::type<cross_signing_key_2_t>) { return knot::schema<cross_signing_key_2_t>(); }
    };
    struct cross_signing_key_3_t {
      struct usage_item_values {
        struct master {
          static constexpr std::string_view json_value = "master";
          friend constexpr bool operator==(master, master) = default;
        };
        struct self_signing {
          static constexpr std::string_view json_value = "self_signing";
          friend constexpr bool operator==(self_signing, self_signing) = default;
        };
        struct user_signing {
          static constexpr std::string_view json_value = "user_signing";
          friend constexpr bool operator==(user_signing, user_signing) = default;
        };
      };
      using usage_item_t = std::variant<usage_item_values::master, usage_item_values::self_signing, usage_item_values::user_signing, std::string>;
      std::string user_id;
      std::vector<usage_item_t> usage;
      std::map<std::string, std::string> keys;
      std::optional<knot::value> signatures;
      friend consteval auto json_schema(knot::type<cross_signing_key_3_t>) { return knot::schema<cross_signing_key_3_t>(); }
    };
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>(); }
    };
    std::optional<cross_signing_key_t> master_key;
    std::optional<cross_signing_key_2_t> self_signing_key;
    std::optional<cross_signing_key_3_t> user_signing_key;
    std::optional<authentication_data_t> auth;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/keys/device_signing/upload";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/keys/signatures/upload: Upload cross-signing signatures.
struct upload_cross_signing_signatures {
  struct response_t {
    std::optional<std::map<std::string, std::map<std::string, knot::value>>> failures;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::map<std::string, std::map<std::string, knot::value>> body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/keys/signatures/upload";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
