// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec: do not edit.
// What the client-server API's operations share.
export module loom.cs.definitions;

import std;
export import knot;
export import loom.ev;

export namespace loom::cs::def {

struct request_email_validation_t {
  std::string client_secret;
  std::string email;
  std::int64_t send_attempt;
  std::optional<std::string> next_link;
  std::optional<std::string> id_server;
  std::optional<std::string> id_access_token;
  friend consteval auto json_schema(knot::type<request_email_validation_t>) { return knot::schema<request_email_validation_t>(); }
};
struct request_token_response_t {
  std::string sid;
  std::optional<std::string> submit_url;
  friend consteval auto json_schema(knot::type<request_token_response_t>) { return knot::schema<request_token_response_t>(); }
};
struct request_msisdn_validation_t {
  std::string client_secret;
  std::string country;
  std::string phone_number;
  std::int64_t send_attempt;
  std::optional<std::string> next_link;
  std::optional<std::string> id_server;
  std::optional<std::string> id_access_token;
  friend consteval auto json_schema(knot::type<request_msisdn_validation_t>) { return knot::schema<request_msisdn_validation_t>(); }
};
struct boolean_capability_t {
  bool enabled;
  friend consteval auto json_schema(knot::type<boolean_capability_t>) { return knot::schema<boolean_capability_t>(); }
};
struct invite3pid_t {
  std::string id_server;
  std::string id_access_token;
  std::string medium;
  std::string address;
  friend consteval auto json_schema(knot::type<invite3pid_t>) { return knot::schema<invite3pid_t>(); }
};
struct device_t {
  std::string device_id;
  std::optional<std::string> display_name;
  std::optional<std::string> last_seen_ip;
  std::optional<std::int64_t> last_seen_ts;
  friend consteval auto json_schema(knot::type<device_t>) { return knot::schema<device_t>(); }
};
struct filter_t {
  struct event_format_values {
    struct client {
      static constexpr std::string_view json_value = "client";
      friend constexpr bool operator==(client, client) = default;
    };
    struct federation {
      static constexpr std::string_view json_value = "federation";
      friend constexpr bool operator==(federation, federation) = default;
    };
  };
  using event_format_t = std::variant<event_format_values::client, event_format_values::federation, std::string>;
  struct event_filter_t {
    std::optional<std::int64_t> limit;
    std::optional<std::vector<std::string>> not_senders;
    std::optional<std::vector<std::string>> not_types;
    std::optional<std::vector<std::string>> senders;
    std::optional<std::vector<std::string>> types;
    friend consteval auto json_schema(knot::type<event_filter_t>) { return knot::schema<event_filter_t>(); }
  };
  struct event_filter_2_t {
    std::optional<std::int64_t> limit;
    std::optional<std::vector<std::string>> not_senders;
    std::optional<std::vector<std::string>> not_types;
    std::optional<std::vector<std::string>> senders;
    std::optional<std::vector<std::string>> types;
    friend consteval auto json_schema(knot::type<event_filter_2_t>) { return knot::schema<event_filter_2_t>(); }
  };
  struct room_filter_t {
    struct event_filter_t {
      std::optional<std::int64_t> limit;
      std::optional<std::vector<std::string>> not_senders;
      std::optional<std::vector<std::string>> not_types;
      std::optional<std::vector<std::string>> senders;
      std::optional<std::vector<std::string>> types;
      std::optional<bool> unread_thread_notifications;
      std::optional<bool> lazy_load_members;
      std::optional<bool> include_redundant_members;
      std::optional<std::vector<std::string>> not_rooms;
      std::optional<std::vector<std::string>> rooms;
      std::optional<bool> contains_url;
      friend consteval auto json_schema(knot::type<event_filter_t>) { return knot::schema<event_filter_t>(); }
    };
    struct event_filter_2_t {
      std::optional<std::int64_t> limit;
      std::optional<std::vector<std::string>> not_senders;
      std::optional<std::vector<std::string>> not_types;
      std::optional<std::vector<std::string>> senders;
      std::optional<std::vector<std::string>> types;
      std::optional<bool> unread_thread_notifications;
      std::optional<bool> lazy_load_members;
      std::optional<bool> include_redundant_members;
      std::optional<std::vector<std::string>> not_rooms;
      std::optional<std::vector<std::string>> rooms;
      std::optional<bool> contains_url;
      friend consteval auto json_schema(knot::type<event_filter_2_t>) { return knot::schema<event_filter_2_t>(); }
    };
    struct event_filter_3_t {
      std::optional<std::int64_t> limit;
      std::optional<std::vector<std::string>> not_senders;
      std::optional<std::vector<std::string>> not_types;
      std::optional<std::vector<std::string>> senders;
      std::optional<std::vector<std::string>> types;
      std::optional<bool> unread_thread_notifications;
      std::optional<bool> lazy_load_members;
      std::optional<bool> include_redundant_members;
      std::optional<std::vector<std::string>> not_rooms;
      std::optional<std::vector<std::string>> rooms;
      std::optional<bool> contains_url;
      friend consteval auto json_schema(knot::type<event_filter_3_t>) { return knot::schema<event_filter_3_t>(); }
    };
    struct event_filter_4_t {
      std::optional<std::int64_t> limit;
      std::optional<std::vector<std::string>> not_senders;
      std::optional<std::vector<std::string>> not_types;
      std::optional<std::vector<std::string>> senders;
      std::optional<std::vector<std::string>> types;
      std::optional<bool> unread_thread_notifications;
      std::optional<bool> lazy_load_members;
      std::optional<bool> include_redundant_members;
      std::optional<std::vector<std::string>> not_rooms;
      std::optional<std::vector<std::string>> rooms;
      std::optional<bool> contains_url;
      friend consteval auto json_schema(knot::type<event_filter_4_t>) { return knot::schema<event_filter_4_t>(); }
    };
    std::optional<std::vector<std::string>> not_rooms;
    std::optional<std::vector<std::string>> rooms;
    std::optional<event_filter_t> ephemeral;
    std::optional<bool> include_leave;
    std::optional<event_filter_2_t> state;
    std::optional<event_filter_3_t> timeline;
    std::optional<event_filter_4_t> account_data;
    friend consteval auto json_schema(knot::type<room_filter_t>) { return knot::schema<room_filter_t>(); }
  };
  std::optional<std::vector<std::string>> event_fields;
  std::optional<event_format_t> event_format;
  std::optional<event_filter_t> presence;
  std::optional<event_filter_2_t> account_data;
  std::optional<room_filter_t> room;
  friend consteval auto json_schema(knot::type<filter_t>) { return knot::schema<filter_t>(); }
};
struct key_backup_data_t {
  std::int64_t first_message_index;
  std::int64_t forwarded_count;
  bool is_verified;
  knot::value session_data;
  friend consteval auto json_schema(knot::type<key_backup_data_t>) { return knot::schema<key_backup_data_t>(); }
};
struct room_keys_update_response_t {
  std::string etag;
  std::int64_t count;
  friend consteval auto json_schema(knot::type<room_keys_update_response_t>) { return knot::schema<room_keys_update_response_t>(); }
};
struct room_key_backup_t {
  std::map<std::string, key_backup_data_t> sessions;
  friend consteval auto json_schema(knot::type<room_key_backup_t>) { return knot::schema<room_key_backup_t>(); }
};
using one_time_keys_t = std::map<std::string, knot::value>;
struct published_rooms_chunk_t {
  std::optional<std::string> canonical_alias;
  std::optional<std::string> name;
  std::int64_t num_joined_members;
  std::string room_id;
  std::optional<std::string> topic;
  bool world_readable;
  bool guest_can_join;
  std::optional<std::string> avatar_url;
  std::optional<std::string> join_rule;
  std::optional<std::string> room_type;
  friend consteval auto json_schema(knot::type<published_rooms_chunk_t>) { return knot::schema<published_rooms_chunk_t>(); }
};
struct public_rooms_response_t {
  std::vector<published_rooms_chunk_t> chunk;
  std::optional<std::string> next_batch;
  std::optional<std::string> prev_batch;
  std::optional<std::int64_t> total_room_count_estimate;
  friend consteval auto json_schema(knot::type<public_rooms_response_t>) { return knot::schema<public_rooms_response_t>(); }
};
struct user_identifier_t {
  std::string type;
  friend consteval auto json_schema(knot::type<user_identifier_t>) { return knot::schema<user_identifier_t>(); }
};
struct homeserver_information_t {
  std::string base_url;
  friend consteval auto json_schema(knot::type<homeserver_information_t>) { return knot::schema<homeserver_information_t>(); }
};
struct identity_server_information_t {
  std::string base_url;
  friend consteval auto json_schema(knot::type<identity_server_information_t>) { return knot::schema<identity_server_information_t>(); }
};
struct open_id_credentials_t {
  std::string access_token;
  std::string token_type;
  std::string matrix_server_name;
  std::int64_t expires_in;
  friend consteval auto json_schema(knot::type<open_id_credentials_t>) { return knot::schema<open_id_credentials_t>(); }
};
struct push_condition_t {
  std::string kind;
  std::optional<std::string> key;
  std::optional<std::string> pattern;
  std::optional<std::string> is;
  std::optional<knot::value> value;
  friend consteval auto json_schema(knot::type<push_condition_t>) { return knot::schema<push_condition_t>(); }
};
struct push_rule_t {
  std::vector<knot::value> actions;
  bool default_;
  bool enabled;
  std::string rule_id;
  std::optional<std::vector<push_condition_t>> conditions;
  std::optional<std::string> pattern;
  friend consteval auto json_schema(knot::type<push_rule_t>) { return knot::schema<push_rule_t>().member<"default_">(knot::key("default")); }
};
struct push_ruleset_t {
  std::optional<std::vector<push_rule_t>> content;
  std::optional<std::vector<push_rule_t>> override_;
  std::optional<std::vector<push_rule_t>> room;
  std::optional<std::vector<push_rule_t>> sender;
  std::optional<std::vector<push_rule_t>> underride;
  friend consteval auto json_schema(knot::type<push_ruleset_t>) { return knot::schema<push_ruleset_t>().member<"override_">(knot::key("override")); }
};
struct tag_t {
  std::optional<double> order;
  friend consteval auto json_schema(knot::type<tag_t>) { return knot::schema<tag_t>(); }
};
struct protocol_t {
  struct field_type_t {
    std::string regexp;
    std::string placeholder;
    friend consteval auto json_schema(knot::type<field_type_t>) { return knot::schema<field_type_t>(); }
  };
  struct protocol_instance_t {
    std::string desc;
    std::optional<std::string> icon;
    knot::value fields;
    std::string network_id;
    std::optional<std::string> instance_id;
    friend consteval auto json_schema(knot::type<protocol_instance_t>) { return knot::schema<protocol_instance_t>(); }
  };
  std::vector<std::string> user_fields;
  std::vector<std::string> location_fields;
  std::string icon;
  std::map<std::string, field_type_t> field_types;
  std::vector<protocol_instance_t> instances;
  friend consteval auto json_schema(knot::type<protocol_t>) { return knot::schema<protocol_t>(); }
};
struct location_t {
  std::string alias;
  std::string protocol;
  knot::value fields;
  friend consteval auto json_schema(knot::type<location_t>) { return knot::schema<location_t>(); }
};
struct user_t {
  std::string userid;
  std::string protocol;
  knot::value fields;
  friend consteval auto json_schema(knot::type<user_t>) { return knot::schema<user_t>(); }
};
struct discovery_information_t {
  homeserver_information_t m_homeserver;
  std::optional<identity_server_information_t> m_identity_server;
  friend consteval auto json_schema(knot::type<discovery_information_t>) { return knot::schema<discovery_information_t>().member<"m_homeserver">(knot::key("m.homeserver")).member<"m_identity_server">(knot::key("m.identity_server")); }
};

}  // namespace loom::cs::def
