// Generated by tools/generate.py from matrix-spec device_management.yaml: do not edit.
export module loom.cs.device_management;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/devices: List registered devices for the current user
struct get_devices {
  struct response_t {
    std::optional<std::vector<def::device_t>> devices;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/devices";
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v3/devices/{deviceId}: Get a single device
struct get_device {
  std::string device_id;
  using response = def::device_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/devices/" + percent_encoded(detail::text(device_id));
    return {method::get{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/devices/{deviceId}: Create or update a device
struct update_device {
  struct body_t {
    std::optional<std::string> display_name;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  std::string device_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/devices/" + percent_encoded(detail::text(device_id));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// DELETE /_matrix/client/v3/devices/{deviceId}: Delete a device
struct delete_device {
  struct body_t {
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>(); }
    };
    std::optional<authentication_data_t> auth;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  std::string device_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/devices/" + percent_encoded(detail::text(device_id));
    return {method::delete_{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/delete_devices: Bulk deletion of devices
struct delete_devices {
  struct body_t {
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>(); }
    };
    std::vector<std::string> devices;
    std::optional<authentication_data_t> auth;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/delete_devices";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
