// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec directory.yaml: do not edit.
export module loom.cs.directory;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// PUT /_matrix/client/v3/directory/room/{roomAlias}: Create a new mapping from room alias to room ID.
struct set_room_alias {
  struct body_t {
    std::string room_id;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  std::string room_alias;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/directory/room/" + percent_encoded(detail::text(room_alias));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/directory/room/{roomAlias}: Get the room ID corresponding to this room alias.
struct get_room_id_by_alias {
  struct response_t {
    std::optional<std::string> room_id;
    std::optional<std::vector<std::string>> servers;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_alias;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/directory/room/" + percent_encoded(detail::text(room_alias));
    return {method::get{}, std::move(target), "", false};
  }
};

// DELETE /_matrix/client/v3/directory/room/{roomAlias}: Remove a mapping of room alias to room ID.
struct delete_room_alias {
  std::string room_alias;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/directory/room/" + percent_encoded(detail::text(room_alias));
    return {method::delete_{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v3/rooms/{roomId}/aliases: Get a list of local aliases on a given room.
struct get_local_aliases {
  struct response_t {
    std::vector<std::string> aliases;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/aliases";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
