// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec event_context.yaml: do not edit.
export module loom.cs.event_context;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/rooms/{roomId}/context/{eventId}: Get events and state around the specified event.
struct get_event_context {
  struct response_t {
    struct client_event_t {
      struct unsigned_data_t {
        std::optional<std::int64_t> age;
        std::optional<knot::value> redacted_because;
        std::optional<std::string> transaction_id;
        std::optional<knot::value> prev_content;
        std::optional<std::string> prev_sender;
        std::optional<std::string> replaces_state;
        std::optional<std::string> membership;
        knot::value rest;
        friend consteval auto json_schema(knot::type<unsigned_data_t>) { return knot::schema<unsigned_data_t>().member<"rest">(knot::rest); }
      };
      std::string event_id;
      std::string type;
      std::optional<std::string> state_key;
      std::string sender;
      std::int64_t origin_server_ts;
      knot::value content;
      std::optional<unsigned_data_t> unsigned_;
      std::string room_id;
      knot::value rest;
      friend consteval auto json_schema(knot::type<client_event_t>) { return knot::schema<client_event_t>().member<"unsigned_">(knot::key("unsigned")).member<"rest">(knot::rest); }
    };
    std::optional<std::string> start;
    std::optional<std::string> end;
    std::optional<std::vector<loom::ev::timeline_event>> events_before;
    std::optional<client_event_t> event;
    std::optional<std::vector<loom::ev::timeline_event>> events_after;
    std::optional<std::vector<loom::ev::timeline_event>> state;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  std::string event_id;
  std::optional<std::int64_t> limit;
  std::optional<std::string> filter;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/context/" + percent_encoded(detail::text(event_id));
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (filter)
      detail::query(target, "filter", detail::text((*filter)));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
