// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec event_context.yaml: do not edit.
export module loom.cs.event_context;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/rooms/{roomId}/context/{eventId}: Get events and state around the specified event.
struct get_event_context {
  struct response_t {
    std::optional<std::string> start;
    std::optional<std::string> end;
    std::optional<std::vector<loom::ev::timeline_event>> events_before;
    std::optional<loom::ev::timeline_event> event;
    std::optional<std::vector<loom::ev::timeline_event>> events_after;
    std::optional<std::vector<loom::ev::timeline_event>> state;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  std::string event_id;
  std::optional<std::int64_t> limit;
  std::optional<std::string> filter;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/context/" + percent_encoded(detail::text(event_id));
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (filter)
      detail::query(target, "filter", detail::text((*filter)));
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
