// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec filter.yaml: do not edit.
export module loom.cs.filter;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/user/{userId}/filter: Upload a new filter.
struct define_filter {
  struct filter_t {
    struct event_format_values {
      struct client {
        static constexpr std::string_view json_value = "client";
        friend constexpr bool operator==(client, client) = default;
      };
      struct federation {
        static constexpr std::string_view json_value = "federation";
        friend constexpr bool operator==(federation, federation) = default;
      };
    };
    using event_format_t = std::variant<event_format_values::client, event_format_values::federation, std::string>;
    struct event_filter_t {
      std::optional<std::int64_t> limit;
      std::optional<std::vector<std::string>> not_senders;
      std::optional<std::vector<std::string>> not_types;
      std::optional<std::vector<std::string>> senders;
      std::optional<std::vector<std::string>> types;
      knot::value rest;
      friend consteval auto json_schema(knot::type<event_filter_t>) { return knot::schema<event_filter_t>().member<"rest">(knot::rest); }
    };
    struct event_filter_2_t {
      std::optional<std::int64_t> limit;
      std::optional<std::vector<std::string>> not_senders;
      std::optional<std::vector<std::string>> not_types;
      std::optional<std::vector<std::string>> senders;
      std::optional<std::vector<std::string>> types;
      knot::value rest;
      friend consteval auto json_schema(knot::type<event_filter_2_t>) { return knot::schema<event_filter_2_t>().member<"rest">(knot::rest); }
    };
    struct room_filter_t {
      struct event_filter_t {
        std::optional<std::int64_t> limit;
        std::optional<std::vector<std::string>> not_senders;
        std::optional<std::vector<std::string>> not_types;
        std::optional<std::vector<std::string>> senders;
        std::optional<std::vector<std::string>> types;
        std::optional<bool> unread_thread_notifications;
        std::optional<bool> lazy_load_members;
        std::optional<bool> include_redundant_members;
        std::optional<std::vector<std::string>> not_rooms;
        std::optional<std::vector<std::string>> rooms;
        std::optional<bool> contains_url;
        knot::value rest;
        friend consteval auto json_schema(knot::type<event_filter_t>) { return knot::schema<event_filter_t>().member<"rest">(knot::rest); }
      };
      struct event_filter_2_t {
        std::optional<std::int64_t> limit;
        std::optional<std::vector<std::string>> not_senders;
        std::optional<std::vector<std::string>> not_types;
        std::optional<std::vector<std::string>> senders;
        std::optional<std::vector<std::string>> types;
        std::optional<bool> unread_thread_notifications;
        std::optional<bool> lazy_load_members;
        std::optional<bool> include_redundant_members;
        std::optional<std::vector<std::string>> not_rooms;
        std::optional<std::vector<std::string>> rooms;
        std::optional<bool> contains_url;
        knot::value rest;
        friend consteval auto json_schema(knot::type<event_filter_2_t>) { return knot::schema<event_filter_2_t>().member<"rest">(knot::rest); }
      };
      struct event_filter_3_t {
        std::optional<std::int64_t> limit;
        std::optional<std::vector<std::string>> not_senders;
        std::optional<std::vector<std::string>> not_types;
        std::optional<std::vector<std::string>> senders;
        std::optional<std::vector<std::string>> types;
        std::optional<bool> unread_thread_notifications;
        std::optional<bool> lazy_load_members;
        std::optional<bool> include_redundant_members;
        std::optional<std::vector<std::string>> not_rooms;
        std::optional<std::vector<std::string>> rooms;
        std::optional<bool> contains_url;
        knot::value rest;
        friend consteval auto json_schema(knot::type<event_filter_3_t>) { return knot::schema<event_filter_3_t>().member<"rest">(knot::rest); }
      };
      struct event_filter_4_t {
        std::optional<std::int64_t> limit;
        std::optional<std::vector<std::string>> not_senders;
        std::optional<std::vector<std::string>> not_types;
        std::optional<std::vector<std::string>> senders;
        std::optional<std::vector<std::string>> types;
        std::optional<bool> unread_thread_notifications;
        std::optional<bool> lazy_load_members;
        std::optional<bool> include_redundant_members;
        std::optional<std::vector<std::string>> not_rooms;
        std::optional<std::vector<std::string>> rooms;
        std::optional<bool> contains_url;
        knot::value rest;
        friend consteval auto json_schema(knot::type<event_filter_4_t>) { return knot::schema<event_filter_4_t>().member<"rest">(knot::rest); }
      };
      std::optional<std::vector<std::string>> not_rooms;
      std::optional<std::vector<std::string>> rooms;
      std::optional<event_filter_t> ephemeral;
      std::optional<bool> include_leave;
      std::optional<event_filter_2_t> state;
      std::optional<event_filter_3_t> timeline;
      std::optional<event_filter_4_t> account_data;
      knot::value rest;
      friend consteval auto json_schema(knot::type<room_filter_t>) { return knot::schema<room_filter_t>().member<"rest">(knot::rest); }
    };
    std::optional<std::vector<std::string>> event_fields;
    std::optional<event_format_t> event_format;
    std::optional<event_filter_t> presence;
    std::optional<event_filter_2_t> account_data;
    std::optional<room_filter_t> room;
    knot::value rest;
    friend consteval auto json_schema(knot::type<filter_t>) { return knot::schema<filter_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    std::string filter_id;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  filter_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/filter";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/user/{userId}/filter/{filterId}: Download a filter
struct get_filter {
  std::string user_id;
  std::string filter_id;
  using response = def::filter_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/filter/" + percent_encoded(detail::text(filter_id));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
