// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec joining.yaml: do not edit.
export module loom.cs.joining;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/rooms/{roomId}/join: Join the requesting user to a particular room.
struct join_room_by_id {
  struct body_t {
    struct third_party_signed_t {
      std::string sender;
      std::string mxid;
      std::string token;
      std::map<std::string, std::map<std::string, std::string>> signatures;
      friend consteval auto json_schema(knot::type<third_party_signed_t>) { return knot::schema<third_party_signed_t>(); }
    };
    std::optional<third_party_signed_t> third_party_signed;
    std::optional<std::string> reason;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    std::string room_id;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/join";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/join/{roomIdOrAlias}: Join the requesting user to a particular room.
struct join_room {
  struct body_t {
    struct third_party_signed_t {
      std::string sender;
      std::string mxid;
      std::string token;
      std::map<std::string, std::map<std::string, std::string>> signatures;
      friend consteval auto json_schema(knot::type<third_party_signed_t>) { return knot::schema<third_party_signed_t>(); }
    };
    std::optional<third_party_signed_t> third_party_signed;
    std::optional<std::string> reason;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    std::string room_id;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id_or_alias;
  std::optional<std::vector<std::string>> via;
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/join/" + percent_encoded(detail::text(room_id_or_alias));
    if (via)
      for (const auto& one : (*via)) detail::query(target, "via", detail::text(one));
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
