// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec key_backup.yaml: do not edit.
export module loom.cs.key_backup;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/room_keys/version: Create a new backup.
struct post_room_keys_version {
  struct body_t {
    struct algorithm_values {
      struct m_megolm_backup_v1_curve25519_aes_sha2 {
        static constexpr std::string_view json_value = "m.megolm_backup.v1.curve25519-aes-sha2";
        friend constexpr bool operator==(m_megolm_backup_v1_curve25519_aes_sha2, m_megolm_backup_v1_curve25519_aes_sha2) = default;
      };
    };
    using algorithm_t = std::variant<algorithm_values::m_megolm_backup_v1_curve25519_aes_sha2, std::string>;
    algorithm_t algorithm;
    knot::value auth_data;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    std::string version;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/version";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/room_keys/version: Get information about the latest backup version.
struct get_room_keys_version_current {
  struct response_t {
    struct algorithm_values {
      struct m_megolm_backup_v1_curve25519_aes_sha2 {
        static constexpr std::string_view json_value = "m.megolm_backup.v1.curve25519-aes-sha2";
        friend constexpr bool operator==(m_megolm_backup_v1_curve25519_aes_sha2, m_megolm_backup_v1_curve25519_aes_sha2) = default;
      };
    };
    using algorithm_t = std::variant<algorithm_values::m_megolm_backup_v1_curve25519_aes_sha2, std::string>;
    algorithm_t algorithm;
    knot::value auth_data;
    std::int64_t count;
    std::string etag;
    std::string version;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/version";
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v3/room_keys/version/{version}: Get information about an existing backup.
struct get_room_keys_version {
  struct response_t {
    struct algorithm_values {
      struct m_megolm_backup_v1_curve25519_aes_sha2 {
        static constexpr std::string_view json_value = "m.megolm_backup.v1.curve25519-aes-sha2";
        friend constexpr bool operator==(m_megolm_backup_v1_curve25519_aes_sha2, m_megolm_backup_v1_curve25519_aes_sha2) = default;
      };
    };
    using algorithm_t = std::variant<algorithm_values::m_megolm_backup_v1_curve25519_aes_sha2, std::string>;
    algorithm_t algorithm;
    knot::value auth_data;
    std::int64_t count;
    std::string etag;
    std::string version;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string version;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/version/" + percent_encoded(detail::text(version));
    return {method::get{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/room_keys/version/{version}: Update information about an existing backup.
struct put_room_keys_version {
  struct body_t {
    struct algorithm_values {
      struct m_megolm_backup_v1_curve25519_aes_sha2 {
        static constexpr std::string_view json_value = "m.megolm_backup.v1.curve25519-aes-sha2";
        friend constexpr bool operator==(m_megolm_backup_v1_curve25519_aes_sha2, m_megolm_backup_v1_curve25519_aes_sha2) = default;
      };
    };
    using algorithm_t = std::variant<algorithm_values::m_megolm_backup_v1_curve25519_aes_sha2, std::string>;
    algorithm_t algorithm;
    knot::value auth_data;
    std::optional<std::string> version;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::string version;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/version/" + percent_encoded(detail::text(version));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// DELETE /_matrix/client/v3/room_keys/version/{version}: Delete an existing key backup.
struct delete_room_keys_version {
  std::string version;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/version/" + percent_encoded(detail::text(version));
    return {method::delete_{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/room_keys/keys/{roomId}/{sessionId}: Store a key in the backup.
struct put_room_key_by_session_id {
  std::string version;
  std::string room_id;
  std::string session_id;
  def::key_backup_data_t body;
  using response = def::room_keys_update_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys/" + percent_encoded(detail::text(room_id)) + "/" + percent_encoded(detail::text(session_id));
    detail::query(target, "version", detail::text(version));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/room_keys/keys/{roomId}/{sessionId}: Retrieve a key from the backup.
struct get_room_key_by_session_id {
  std::string version;
  std::string room_id;
  std::string session_id;
  using response = def::key_backup_data_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys/" + percent_encoded(detail::text(room_id)) + "/" + percent_encoded(detail::text(session_id));
    detail::query(target, "version", detail::text(version));
    return {method::get{}, std::move(target), "", true};
  }
};

// DELETE /_matrix/client/v3/room_keys/keys/{roomId}/{sessionId}: Delete a key from the backup.
struct delete_room_key_by_session_id {
  std::string version;
  std::string room_id;
  std::string session_id;
  using response = def::room_keys_update_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys/" + percent_encoded(detail::text(room_id)) + "/" + percent_encoded(detail::text(session_id));
    detail::query(target, "version", detail::text(version));
    return {method::delete_{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/room_keys/keys/{roomId}: Store several keys in the backup for a given room.
struct put_room_keys_by_room_id {
  std::string version;
  std::string room_id;
  def::room_key_backup_t body;
  using response = def::room_keys_update_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys/" + percent_encoded(detail::text(room_id));
    detail::query(target, "version", detail::text(version));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/room_keys/keys/{roomId}: Retrieve the keys from the backup for a given room.
struct get_room_keys_by_room_id {
  std::string version;
  std::string room_id;
  using response = def::room_key_backup_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys/" + percent_encoded(detail::text(room_id));
    detail::query(target, "version", detail::text(version));
    return {method::get{}, std::move(target), "", true};
  }
};

// DELETE /_matrix/client/v3/room_keys/keys/{roomId}: Delete the keys from the backup for a given room.
struct delete_room_keys_by_room_id {
  std::string version;
  std::string room_id;
  using response = def::room_keys_update_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys/" + percent_encoded(detail::text(room_id));
    detail::query(target, "version", detail::text(version));
    return {method::delete_{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/room_keys/keys: Store several keys in the backup.
struct put_room_keys {
  struct body_t {
    struct room_key_backup_t {
      std::map<std::string, def::key_backup_data_t> sessions;
      knot::value rest;
      friend consteval auto json_schema(knot::type<room_key_backup_t>) { return knot::schema<room_key_backup_t>().member<"rest">(knot::rest); }
    };
    std::map<std::string, room_key_backup_t> rooms;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::string version;
  body_t body;
  using response = def::room_keys_update_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys";
    detail::query(target, "version", detail::text(version));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/room_keys/keys: Retrieve the keys from the backup.
struct get_room_keys {
  struct response_t {
    struct room_key_backup_t {
      std::map<std::string, def::key_backup_data_t> sessions;
      knot::value rest;
      friend consteval auto json_schema(knot::type<room_key_backup_t>) { return knot::schema<room_key_backup_t>().member<"rest">(knot::rest); }
    };
    std::map<std::string, room_key_backup_t> rooms;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string version;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys";
    detail::query(target, "version", detail::text(version));
    return {method::get{}, std::move(target), "", true};
  }
};

// DELETE /_matrix/client/v3/room_keys/keys: Delete the keys from the backup.
struct delete_room_keys {
  std::string version;
  using response = def::room_keys_update_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/room_keys/keys";
    detail::query(target, "version", detail::text(version));
    return {method::delete_{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
