// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec knocking.yaml: do not edit.
export module loom.cs.knocking;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/knock/{roomIdOrAlias}: Knock on a room, requesting permission to join.
struct knock_room {
  struct body_t {
    std::optional<std::string> reason;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    std::string room_id;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id_or_alias;
  std::optional<std::vector<std::string>> via;
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/knock/" + percent_encoded(detail::text(room_id_or_alias));
    if (via)
      for (const auto& one : (*via)) detail::query(target, "via", detail::text(one));
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
