// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec leaving.yaml: do not edit.
export module loom.cs.leaving;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/rooms/{roomId}/leave: Stop the requesting user participating in a particular room.
struct leave_room {
  struct body_t {
    std::optional<std::string> reason;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  body_t body;
  using response = knot::raw;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/leave";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/rooms/{roomId}/forget: Stop the requesting user remembering about a particular room.
struct forget_room {
  std::string room_id;
  using response = knot::raw;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/forget";
    return {method::post{}, std::move(target), "{}", true};
  }
};
}  // namespace loom::cs
