// Generated by tools/generate.py from matrix-spec list_joined_rooms.yaml: do not edit.
export module loom.cs.list_joined_rooms;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/joined_rooms: Lists the user's current rooms.
struct get_joined_rooms {
  struct response_t {
    std::vector<std::string> joined_rooms;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/joined_rooms";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
