// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec list_public_rooms.yaml: do not edit.
export module loom.cs.list_public_rooms;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/directory/list/room/{roomId}: Gets the visibility of a room in the directory
struct get_room_visibility_on_directory {
  struct response_t {
    struct visibility_values {
      struct private_ {
        static constexpr std::string_view json_value = "private";
        friend constexpr bool operator==(private_, private_) = default;
      };
      struct public_ {
        static constexpr std::string_view json_value = "public";
        friend constexpr bool operator==(public_, public_) = default;
      };
    };
    using visibility_t = splice::variant<visibility_values::private_, visibility_values::public_, std::string>;
    std::optional<visibility_t> visibility;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/directory/list/room/" + percent_encoded(detail::text(room_id));
    return {method::get{}, std::move(target), "", false};
  }
};

// PUT /_matrix/client/v3/directory/list/room/{roomId}: Sets the visibility of a room in the directory
struct set_room_visibility_on_directory {
  struct body_t {
    struct visibility_values {
      struct private_ {
        static constexpr std::string_view json_value = "private";
        friend constexpr bool operator==(private_, private_) = default;
      };
      struct public_ {
        static constexpr std::string_view json_value = "public";
        friend constexpr bool operator==(public_, public_) = default;
      };
    };
    using visibility_t = splice::variant<visibility_values::private_, visibility_values::public_, std::string>;
    std::optional<visibility_t> visibility;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  body_t body;
  using response = knot::raw;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/directory/list/room/" + percent_encoded(detail::text(room_id));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/publicRooms: Lists a server's published room directory
struct get_public_rooms {
  std::optional<std::int64_t> limit;
  std::optional<std::string> since;
  std::optional<std::string> server;
  using response = def::public_rooms_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/publicRooms";
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (since)
      detail::query(target, "since", detail::text((*since)));
    if (server)
      detail::query(target, "server", detail::text((*server)));
    return {method::get{}, std::move(target), "", false};
  }
};

// POST /_matrix/client/v3/publicRooms: Lists a server's published room directory with an optional filter
struct query_public_rooms {
  struct body_t {
    struct filter_t {
      std::optional<std::string> generic_search_term;
      std::optional<std::vector<std::string>> room_types;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<filter_t>) { return knot::schema<filter_t>().member<"rest">(knot::rest); }
    };
    std::optional<std::int64_t> limit;
    std::optional<std::string> since;
    std::optional<filter_t> filter;
    std::optional<bool> include_all_networks;
    std::optional<std::string> third_party_instance_id;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::optional<std::string> server;
  body_t body;
  using response = def::public_rooms_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/publicRooms";
    if (server)
      detail::query(target, "server", detail::text((*server)));
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
