// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec login_token.yaml: do not edit.
export module loom.cs.login_token;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v1/login/get_token: Optional endpoint to generate a single-use, time-limited, `m.login.token` token.
struct generate_login_token {
  struct body_t {
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      knot::value rest;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>().member<"rest">(knot::rest); }
    };
    std::optional<authentication_data_t> auth;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    std::string login_token;
    std::int64_t expires_in_ms;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/login/get_token";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
