// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec login.yaml: do not edit.
export module loom.cs.login;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/login: Get the supported login types to authenticate users
struct get_login_flows {
  struct response_t {
    struct login_flow_t {
      std::string type;
      std::optional<bool> get_login_token;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<login_flow_t>) { return knot::schema<login_flow_t>().member<"rest">(knot::rest); }
    };
    std::optional<std::vector<login_flow_t>> flows;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/login";
    return {method::get{}, std::move(target), "", false};
  }
};

// POST /_matrix/client/v3/login: Authenticates the user.
struct login {
  struct body_t {
    std::string type;
    std::optional<def::user_identifier_t> identifier;
    std::optional<std::string> user;
    std::optional<std::string> medium;
    std::optional<std::string> address;
    std::optional<std::string> password;
    std::optional<std::string> token;
    std::optional<std::string> device_id;
    std::optional<std::string> initial_device_display_name;
    std::optional<bool> refresh_token;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    struct discovery_information_t {
      def::homeserver_information_t m_homeserver;
      std::optional<def::identity_server_information_t> m_identity_server;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<discovery_information_t>) { return knot::schema<discovery_information_t>().member<"m_homeserver">(knot::key("m.homeserver")).member<"m_identity_server">(knot::key("m.identity_server")).member<"rest">(knot::rest); }
    };
    std::string user_id;
    std::string access_token;
    std::optional<std::string> refresh_token;
    std::optional<std::int64_t> expires_in_ms;
    std::optional<std::string> home_server;
    std::string device_id;
    std::optional<discovery_information_t> well_known;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/login";
    return {method::post{}, std::move(target), detail::json(body), false};
  }
};
}  // namespace loom::cs
