// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec logout.yaml: do not edit.
export module loom.cs.logout;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/logout: Invalidates a user access token
struct logout {
  using response = knot::raw;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/logout";
    return {method::post{}, std::move(target), "{}", true};
  }
};

// POST /_matrix/client/v3/logout/all: Invalidates all access tokens for a user
struct logout_all {
  using response = knot::raw;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/logout/all";
    return {method::post{}, std::move(target), "{}", true};
  }
};
}  // namespace loom::cs
