// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec message_pagination.yaml: do not edit.
export module loom.cs.message_pagination;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/rooms/{roomId}/messages: Get a list of events for this room
struct get_room_events {
  struct dir_values {
    struct b {
      static constexpr std::string_view json_value = "b";
      friend constexpr bool operator==(b, b) = default;
    };
    struct f {
      static constexpr std::string_view json_value = "f";
      friend constexpr bool operator==(f, f) = default;
    };
  };
  using dir_t = std::variant<dir_values::b, dir_values::f, std::string>;
  struct response_t {
    std::string start;
    std::optional<std::string> end;
    std::vector<def::client_event_t> chunk;
    std::optional<std::vector<def::client_event_t>> state;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  std::optional<std::string> from;
  std::optional<std::string> to;
  dir_t dir;
  std::optional<std::int64_t> limit;
  std::optional<std::string> filter;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/messages";
    if (from)
      detail::query(target, "from", detail::text((*from)));
    if (to)
      detail::query(target, "to", detail::text((*to)));
    detail::query(target, "dir", detail::text(dir));
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (filter)
      detail::query(target, "filter", detail::text((*filter)));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
