// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec mutual_rooms.yaml: do not edit.
export module loom.cs.mutual_rooms;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/mutual_rooms: Get the list of rooms that the user shares with another user.
struct get_mutual_rooms {
  struct response_t {
    std::vector<std::string> joined;
    std::int64_t count;
    std::optional<std::string> next_batch;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  std::optional<std::string> from;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/mutual_rooms";
    detail::query(target, "user_id", detail::text(user_id));
    if (from)
      detail::query(target, "from", detail::text((*from)));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
