// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec oauth_server_metadata.yaml: do not edit.
export module loom.cs.oauth_server_metadata;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/auth_metadata: Get the OAuth 2.0 authorisation server metadata.
struct get_auth_metadata {
  struct response_t {
    struct account_management_actions_supported_item_values {
      struct org_matrix_profile {
        static constexpr std::string_view json_value = "org.matrix.profile";
        friend constexpr bool operator==(org_matrix_profile, org_matrix_profile) = default;
      };
      struct org_matrix_devices_list {
        static constexpr std::string_view json_value = "org.matrix.devices_list";
        friend constexpr bool operator==(org_matrix_devices_list, org_matrix_devices_list) = default;
      };
      struct org_matrix_device_view {
        static constexpr std::string_view json_value = "org.matrix.device_view";
        friend constexpr bool operator==(org_matrix_device_view, org_matrix_device_view) = default;
      };
      struct org_matrix_device_delete {
        static constexpr std::string_view json_value = "org.matrix.device_delete";
        friend constexpr bool operator==(org_matrix_device_delete, org_matrix_device_delete) = default;
      };
      struct org_matrix_account_deactivate {
        static constexpr std::string_view json_value = "org.matrix.account_deactivate";
        friend constexpr bool operator==(org_matrix_account_deactivate, org_matrix_account_deactivate) = default;
      };
      struct org_matrix_cross_signing_reset {
        static constexpr std::string_view json_value = "org.matrix.cross_signing_reset";
        friend constexpr bool operator==(org_matrix_cross_signing_reset, org_matrix_cross_signing_reset) = default;
      };
    };
    using account_management_actions_supported_item_t = std::variant<account_management_actions_supported_item_values::org_matrix_profile, account_management_actions_supported_item_values::org_matrix_devices_list, account_management_actions_supported_item_values::org_matrix_device_view, account_management_actions_supported_item_values::org_matrix_device_delete, account_management_actions_supported_item_values::org_matrix_account_deactivate, account_management_actions_supported_item_values::org_matrix_cross_signing_reset, std::string>;
    std::string issuer;
    std::string authorization_endpoint;
    std::string token_endpoint;
    std::string revocation_endpoint;
    std::string registration_endpoint;
    std::vector<std::string> response_types_supported;
    std::vector<std::string> grant_types_supported;
    std::vector<std::string> response_modes_supported;
    std::vector<std::string> code_challenge_methods_supported;
    std::optional<std::vector<std::string>> prompt_values_supported;
    std::optional<std::string> account_management_uri;
    std::optional<std::vector<account_management_actions_supported_item_t>> account_management_actions_supported;
    std::optional<std::string> device_authorization_endpoint;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/auth_metadata";
    return {method::get{}, std::move(target), "", false};
  }
};
}  // namespace loom::cs
