// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec old_sync.yaml: do not edit.
export module loom.cs.old_sync;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/events: Listen on the event stream. (deprecated)
struct get_events {
  struct response_t {
    std::optional<std::string> start;
    std::optional<std::string> end;
    std::optional<std::vector<loom::ev::timeline_event>> chunk;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::optional<std::string> from;
  std::optional<std::int64_t> timeout;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/events";
    if (from)
      detail::query(target, "from", detail::text((*from)));
    if (timeout)
      detail::query(target, "timeout", detail::text((*timeout)));
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/client/v3/initialSync: Get the user's current state. (deprecated)
struct initial_sync {
  struct response_t {
    struct room_info_t {
      struct membership_values {
        struct invite {
          static constexpr std::string_view json_value = "invite";
          friend constexpr bool operator==(invite, invite) = default;
        };
        struct join {
          static constexpr std::string_view json_value = "join";
          friend constexpr bool operator==(join, join) = default;
        };
        struct leave {
          static constexpr std::string_view json_value = "leave";
          friend constexpr bool operator==(leave, leave) = default;
        };
        struct ban {
          static constexpr std::string_view json_value = "ban";
          friend constexpr bool operator==(ban, ban) = default;
        };
      };
      using membership_t = splice::variant<membership_values::invite, membership_values::join, membership_values::leave, membership_values::ban, std::string>;
      struct invite_event_t {
        struct unsigned_data_t {
          std::optional<std::int64_t> age;
          std::optional<loom::ev::timeline_event> redacted_because;
          std::optional<std::string> transaction_id;
          std::optional<knot::raw> prev_content;
          std::optional<std::string> prev_sender;
          std::optional<std::string> replaces_state;
          std::optional<std::string> membership;
          knot::raw rest;
          friend consteval auto json_schema(knot::type<unsigned_data_t>) { return knot::schema<unsigned_data_t>().member<"rest">(knot::rest); }
        };
        std::string event_id;
        std::string type;
        std::optional<std::string> state_key;
        std::string sender;
        std::int64_t origin_server_ts;
        knot::raw content;
        std::optional<unsigned_data_t> unsigned_;
        std::string room_id;
        knot::raw rest;
        friend consteval auto json_schema(knot::type<invite_event_t>) { return knot::schema<invite_event_t>().member<"unsigned_">(knot::key("unsigned")).member<"rest">(knot::rest); }
      };
      struct pagination_chunk_t {
        std::optional<std::string> start;
        std::string end;
        std::vector<loom::ev::timeline_event> chunk;
        knot::raw rest;
        friend consteval auto json_schema(knot::type<pagination_chunk_t>) { return knot::schema<pagination_chunk_t>().member<"rest">(knot::rest); }
      };
      struct visibility_values {
        struct private_ {
          static constexpr std::string_view json_value = "private";
          friend constexpr bool operator==(private_, private_) = default;
        };
        struct public_ {
          static constexpr std::string_view json_value = "public";
          friend constexpr bool operator==(public_, public_) = default;
        };
      };
      using visibility_t = splice::variant<visibility_values::private_, visibility_values::public_, std::string>;
      std::string room_id;
      membership_t membership;
      std::optional<invite_event_t> invite;
      std::optional<pagination_chunk_t> messages;
      std::optional<std::vector<loom::ev::timeline_event>> state;
      std::optional<visibility_t> visibility;
      std::optional<std::vector<loom::ev::basic_event<loom::ev::other_content>>> account_data;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<room_info_t>) { return knot::schema<room_info_t>().member<"rest">(knot::rest); }
    };
    std::string end;
    std::vector<loom::ev::basic_event<loom::ev::other_content>> presence;
    std::vector<room_info_t> rooms;
    std::optional<std::vector<loom::ev::basic_event<loom::ev::other_content>>> account_data;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::optional<std::int64_t> limit;
  std::optional<bool> archived;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/initialSync";
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (archived)
      detail::query(target, "archived", detail::text((*archived)));
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/client/v3/events/{eventId}: Get a single event by event ID. (deprecated)
struct get_one_event {
  std::string event_id;
  using response = loom::ev::timeline_event;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/events/" + percent_encoded(detail::text(event_id));
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
