// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec openid.yaml: do not edit.
export module loom.cs.openid;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/user/{userId}/openid/request_token: Get an OpenID token object to verify the requester's identity.
struct request_open_id_token {
  std::string user_id;
  knot::raw body;
  using response = def::open_id_credentials_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/openid/request_token";
    return {method::post{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
