// Generated by tools/generate.py from matrix-spec openid.yaml: do not edit.
export module loom.cs.openid;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/user/{userId}/openid/request_token: Get an OpenID token object to verify the requester's identity.
struct request_open_id_token {
  std::string user_id;
  knot::value body;
  using response = def::open_id_credentials_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/openid/request_token";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
