// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec password_management.yaml: do not edit.
export module loom.cs.password_management;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/account/password: Changes a user's password.
struct change_password {
  struct body_t {
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      knot::value rest;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>().member<"rest">(knot::rest); }
    };
    std::string new_password;
    std::optional<bool> logout_devices;
    std::optional<authentication_data_t> auth;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/password";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/account/password/email/requestToken: Requests a validation token be sent to the given email address for the purpose of resetting a user's password
struct request_token_to_reset_password_email {
  def::request_email_validation_t body;
  using response = def::request_token_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/password/email/requestToken";
    return {method::post{}, std::move(target), detail::json(body), false};
  }
};

// POST /_matrix/client/v3/account/password/msisdn/requestToken: Requests a validation token be sent to the given phone number for the purpose of resetting a user's password.
struct request_token_to_reset_password_msisdn {
  def::request_msisdn_validation_t body;
  using response = def::request_token_response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/password/msisdn/requestToken";
    return {method::post{}, std::move(target), detail::json(body), false};
  }
};
}  // namespace loom::cs
