// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec peeking_events.yaml: do not edit.
export module loom.cs.peeking_events;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/events: Listen on the event stream of a particular room.
struct peek_events {
  struct response_t {
    struct event_t {
      struct unsigned_data_t {
        std::optional<std::int64_t> age;
        std::optional<loom::ev::timeline_event> redacted_because;
        std::optional<std::string> transaction_id;
        std::optional<knot::raw> prev_content;
        std::optional<std::string> prev_sender;
        std::optional<std::string> replaces_state;
        std::optional<std::string> membership;
        knot::raw rest;
        friend consteval auto json_schema(knot::type<unsigned_data_t>) { return knot::schema<unsigned_data_t>().member<"rest">(knot::rest); }
      };
      std::string event_id;
      std::string type;
      std::optional<std::string> state_key;
      std::string sender;
      std::int64_t origin_server_ts;
      knot::raw content;
      std::optional<unsigned_data_t> unsigned_;
      std::string room_id;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<event_t>) { return knot::schema<event_t>().member<"unsigned_">(knot::key("unsigned")).member<"rest">(knot::rest); }
    };
    std::optional<std::string> start;
    std::optional<std::string> end;
    std::optional<std::vector<event_t>> chunk;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::optional<std::string> from;
  std::optional<std::int64_t> timeout;
  std::string room_id;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/events";
    if (from)
      detail::query(target, "from", detail::text((*from)));
    if (timeout)
      detail::query(target, "timeout", detail::text((*timeout)));
    detail::query(target, "room_id", detail::text(room_id));
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
