// Generated by tools/generate.py from matrix-spec peeking_events.yaml: do not edit.
export module loom.cs.peeking_events;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/events: Listen on the event stream of a particular room.
struct peek_events {
  struct response_t {
    struct event_t {
      struct unsigned_t {
        std::optional<knot::value> redacted_because;
        friend consteval auto json_schema(knot::type<unsigned_t>) { return knot::schema<unsigned_t>(); }
      };
      std::string event_id;
      std::string type;
      std::optional<std::string> state_key;
      std::string sender;
      std::int64_t origin_server_ts;
      knot::value content;
      std::optional<unsigned_t> unsigned_;
      std::string room_id;
      friend consteval auto json_schema(knot::type<event_t>) { return knot::schema<event_t>().member<"unsigned_">(knot::key("unsigned")); }
    };
    std::optional<std::string> start;
    std::optional<std::string> end;
    std::optional<std::vector<event_t>> chunk;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::optional<std::string> from;
  std::optional<std::int64_t> timeout;
  std::string room_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/events";
    if (from)
      detail::query(target, "from", detail::text((*from)));
    if (timeout)
      detail::query(target, "timeout", detail::text((*timeout)));
    detail::query(target, "room_id", detail::text(room_id));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
