// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec policy_server.yaml: do not edit.
export module loom.cs.policy_server;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /.well-known/matrix/policy_server: Gets information about a Policy Server's configuration, if available.
struct get_wellknown_policy {
  struct response_t {
    struct public_keys_t {
      std::string ed25519;
      knot::value rest;
      friend consteval auto json_schema(knot::type<public_keys_t>) { return knot::schema<public_keys_t>().member<"rest">(knot::rest); }
    };
    public_keys_t public_keys;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/.well-known") + "/matrix/policy_server";
    return {method::get{}, std::move(target), "", false};
  }
};
}  // namespace loom::cs
