// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec presence.yaml: do not edit.
export module loom.cs.presence;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// PUT /_matrix/client/v3/presence/{userId}/status: Update this user's presence state.
struct set_presence {
  struct body_t {
    struct presence_values {
      struct online {
        static constexpr std::string_view json_value = "online";
        friend constexpr bool operator==(online, online) = default;
      };
      struct offline {
        static constexpr std::string_view json_value = "offline";
        friend constexpr bool operator==(offline, offline) = default;
      };
      struct unavailable {
        static constexpr std::string_view json_value = "unavailable";
        friend constexpr bool operator==(unavailable, unavailable) = default;
      };
    };
    using presence_t = splice::variant<presence_values::online, presence_values::offline, presence_values::unavailable, std::string>;
    presence_t presence;
    std::optional<std::string> status_msg;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  body_t body;
  using response = knot::raw;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/presence/" + percent_encoded(detail::text(user_id)) + "/status";
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/presence/{userId}/status: Get this user's presence state.
struct get_presence {
  struct response_t {
    struct presence_values {
      struct online {
        static constexpr std::string_view json_value = "online";
        friend constexpr bool operator==(online, online) = default;
      };
      struct offline {
        static constexpr std::string_view json_value = "offline";
        friend constexpr bool operator==(offline, offline) = default;
      };
      struct unavailable {
        static constexpr std::string_view json_value = "unavailable";
        friend constexpr bool operator==(unavailable, unavailable) = default;
      };
    };
    using presence_t = splice::variant<presence_values::online, presence_values::offline, presence_values::unavailable, std::string>;
    presence_t presence;
    std::optional<std::int64_t> last_active_ago;
    std::optional<std::string> status_msg;
    std::optional<bool> currently_active;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/presence/" + percent_encoded(detail::text(user_id)) + "/status";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
