// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec profile.yaml: do not edit.
export module loom.cs.profile;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// PUT /_matrix/client/v3/profile/{userId}/{keyName}: Set a profile field for a user.
struct set_profile_field {
  std::string user_id;
  std::string key_name;
  knot::value body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/profile/" + percent_encoded(detail::text(user_id)) + "/" + percent_encoded(detail::text(key_name));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/profile/{userId}/{keyName}: Get a profile field for a user.
struct get_profile_field {
  std::string user_id;
  std::string key_name;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/profile/" + percent_encoded(detail::text(user_id)) + "/" + percent_encoded(detail::text(key_name));
    return {method::get{}, std::move(target), "", false};
  }
};

// DELETE /_matrix/client/v3/profile/{userId}/{keyName}: Remove a profile field from a user.
struct delete_profile_field {
  std::string user_id;
  std::string key_name;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/profile/" + percent_encoded(detail::text(user_id)) + "/" + percent_encoded(detail::text(key_name));
    return {method::delete_{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v3/profile/{userId}: Get all profile information for a user.
struct get_user_profile {
  struct response_t {
    std::optional<std::string> avatar_url;
    std::optional<std::string> displayname;
    std::optional<std::string> m_tz;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"m_tz">(knot::key("m.tz")); }
  };
  std::string user_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/profile/" + percent_encoded(detail::text(user_id));
    return {method::get{}, std::move(target), "", false};
  }
};
}  // namespace loom::cs
