// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec pushrules.yaml: do not edit.
export module loom.cs.pushrules;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/pushrules/: Retrieve all push rulesets.
struct get_push_rules {
  struct response_t {
    struct ruleset_t {
      std::optional<std::vector<def::push_rule_t>> content;
      std::optional<std::vector<def::push_rule_t>> override_;
      std::optional<std::vector<def::push_rule_t>> room;
      std::optional<std::vector<def::push_rule_t>> sender;
      std::optional<std::vector<def::push_rule_t>> underride;
      knot::value rest;
      friend consteval auto json_schema(knot::type<ruleset_t>) { return knot::schema<ruleset_t>().member<"override_">(knot::key("override")).member<"rest">(knot::rest); }
    };
    ruleset_t global;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/";
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v3/pushrules/global/: Retrieve all push rules.
struct get_push_rules_global {
  using response = def::push_ruleset_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/global/";
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v3/pushrules/global/{kind}/{ruleId}: Retrieve a push rule.
struct get_push_rule {
  struct kind_values {
    struct override_ {
      static constexpr std::string_view json_value = "override";
      friend constexpr bool operator==(override_, override_) = default;
    };
    struct underride {
      static constexpr std::string_view json_value = "underride";
      friend constexpr bool operator==(underride, underride) = default;
    };
    struct sender {
      static constexpr std::string_view json_value = "sender";
      friend constexpr bool operator==(sender, sender) = default;
    };
    struct room {
      static constexpr std::string_view json_value = "room";
      friend constexpr bool operator==(room, room) = default;
    };
    struct content {
      static constexpr std::string_view json_value = "content";
      friend constexpr bool operator==(content, content) = default;
    };
  };
  using kind_t = std::variant<kind_values::override_, kind_values::underride, kind_values::sender, kind_values::room, kind_values::content, std::string>;
  struct push_rule_t {
    std::vector<knot::value> actions;
    bool default_;
    bool enabled;
    std::string rule_id;
    std::optional<std::vector<def::push_condition_t>> conditions;
    std::optional<std::string> pattern;
    knot::value rest;
    friend consteval auto json_schema(knot::type<push_rule_t>) { return knot::schema<push_rule_t>().member<"default_">(knot::key("default")).member<"rest">(knot::rest); }
  };
  kind_t kind;
  std::string rule_id;
  using response = push_rule_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/global/" + percent_encoded(detail::text(kind)) + "/" + percent_encoded(detail::text(rule_id));
    return {method::get{}, std::move(target), "", true};
  }
};

// DELETE /_matrix/client/v3/pushrules/global/{kind}/{ruleId}: Delete a push rule.
struct delete_push_rule {
  struct kind_values {
    struct override_ {
      static constexpr std::string_view json_value = "override";
      friend constexpr bool operator==(override_, override_) = default;
    };
    struct underride {
      static constexpr std::string_view json_value = "underride";
      friend constexpr bool operator==(underride, underride) = default;
    };
    struct sender {
      static constexpr std::string_view json_value = "sender";
      friend constexpr bool operator==(sender, sender) = default;
    };
    struct room {
      static constexpr std::string_view json_value = "room";
      friend constexpr bool operator==(room, room) = default;
    };
    struct content {
      static constexpr std::string_view json_value = "content";
      friend constexpr bool operator==(content, content) = default;
    };
  };
  using kind_t = std::variant<kind_values::override_, kind_values::underride, kind_values::sender, kind_values::room, kind_values::content, std::string>;
  kind_t kind;
  std::string rule_id;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/global/" + percent_encoded(detail::text(kind)) + "/" + percent_encoded(detail::text(rule_id));
    return {method::delete_{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/pushrules/global/{kind}/{ruleId}: Add or change a push rule.
struct set_push_rule {
  struct kind_values {
    struct override_ {
      static constexpr std::string_view json_value = "override";
      friend constexpr bool operator==(override_, override_) = default;
    };
    struct underride {
      static constexpr std::string_view json_value = "underride";
      friend constexpr bool operator==(underride, underride) = default;
    };
    struct sender {
      static constexpr std::string_view json_value = "sender";
      friend constexpr bool operator==(sender, sender) = default;
    };
    struct room {
      static constexpr std::string_view json_value = "room";
      friend constexpr bool operator==(room, room) = default;
    };
    struct content {
      static constexpr std::string_view json_value = "content";
      friend constexpr bool operator==(content, content) = default;
    };
  };
  using kind_t = std::variant<kind_values::override_, kind_values::underride, kind_values::sender, kind_values::room, kind_values::content, std::string>;
  struct body_t {
    std::vector<knot::value> actions;
    std::optional<std::vector<def::push_condition_t>> conditions;
    std::optional<std::string> pattern;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  kind_t kind;
  std::string rule_id;
  std::optional<std::string> before;
  std::optional<std::string> after;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/global/" + percent_encoded(detail::text(kind)) + "/" + percent_encoded(detail::text(rule_id));
    if (before)
      detail::query(target, "before", detail::text((*before)));
    if (after)
      detail::query(target, "after", detail::text((*after)));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/pushrules/global/{kind}/{ruleId}/enabled: Get whether a push rule is enabled
struct is_push_rule_enabled {
  struct kind_values {
    struct override_ {
      static constexpr std::string_view json_value = "override";
      friend constexpr bool operator==(override_, override_) = default;
    };
    struct underride {
      static constexpr std::string_view json_value = "underride";
      friend constexpr bool operator==(underride, underride) = default;
    };
    struct sender {
      static constexpr std::string_view json_value = "sender";
      friend constexpr bool operator==(sender, sender) = default;
    };
    struct room {
      static constexpr std::string_view json_value = "room";
      friend constexpr bool operator==(room, room) = default;
    };
    struct content {
      static constexpr std::string_view json_value = "content";
      friend constexpr bool operator==(content, content) = default;
    };
  };
  using kind_t = std::variant<kind_values::override_, kind_values::underride, kind_values::sender, kind_values::room, kind_values::content, std::string>;
  struct response_t {
    bool enabled;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  kind_t kind;
  std::string rule_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/global/" + percent_encoded(detail::text(kind)) + "/" + percent_encoded(detail::text(rule_id)) + "/enabled";
    return {method::get{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/pushrules/global/{kind}/{ruleId}/enabled: Enable or disable a push rule.
struct set_push_rule_enabled {
  struct kind_values {
    struct override_ {
      static constexpr std::string_view json_value = "override";
      friend constexpr bool operator==(override_, override_) = default;
    };
    struct underride {
      static constexpr std::string_view json_value = "underride";
      friend constexpr bool operator==(underride, underride) = default;
    };
    struct sender {
      static constexpr std::string_view json_value = "sender";
      friend constexpr bool operator==(sender, sender) = default;
    };
    struct room {
      static constexpr std::string_view json_value = "room";
      friend constexpr bool operator==(room, room) = default;
    };
    struct content {
      static constexpr std::string_view json_value = "content";
      friend constexpr bool operator==(content, content) = default;
    };
  };
  using kind_t = std::variant<kind_values::override_, kind_values::underride, kind_values::sender, kind_values::room, kind_values::content, std::string>;
  struct body_t {
    bool enabled;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  kind_t kind;
  std::string rule_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/global/" + percent_encoded(detail::text(kind)) + "/" + percent_encoded(detail::text(rule_id)) + "/enabled";
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// GET /_matrix/client/v3/pushrules/global/{kind}/{ruleId}/actions: The actions for a push rule
struct get_push_rule_actions {
  struct kind_values {
    struct override_ {
      static constexpr std::string_view json_value = "override";
      friend constexpr bool operator==(override_, override_) = default;
    };
    struct underride {
      static constexpr std::string_view json_value = "underride";
      friend constexpr bool operator==(underride, underride) = default;
    };
    struct sender {
      static constexpr std::string_view json_value = "sender";
      friend constexpr bool operator==(sender, sender) = default;
    };
    struct room {
      static constexpr std::string_view json_value = "room";
      friend constexpr bool operator==(room, room) = default;
    };
    struct content {
      static constexpr std::string_view json_value = "content";
      friend constexpr bool operator==(content, content) = default;
    };
  };
  using kind_t = std::variant<kind_values::override_, kind_values::underride, kind_values::sender, kind_values::room, kind_values::content, std::string>;
  struct response_t {
    std::vector<knot::value> actions;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  kind_t kind;
  std::string rule_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/global/" + percent_encoded(detail::text(kind)) + "/" + percent_encoded(detail::text(rule_id)) + "/actions";
    return {method::get{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/pushrules/global/{kind}/{ruleId}/actions: Set the actions for a push rule.
struct set_push_rule_actions {
  struct kind_values {
    struct override_ {
      static constexpr std::string_view json_value = "override";
      friend constexpr bool operator==(override_, override_) = default;
    };
    struct underride {
      static constexpr std::string_view json_value = "underride";
      friend constexpr bool operator==(underride, underride) = default;
    };
    struct sender {
      static constexpr std::string_view json_value = "sender";
      friend constexpr bool operator==(sender, sender) = default;
    };
    struct room {
      static constexpr std::string_view json_value = "room";
      friend constexpr bool operator==(room, room) = default;
    };
    struct content {
      static constexpr std::string_view json_value = "content";
      friend constexpr bool operator==(content, content) = default;
    };
  };
  using kind_t = std::variant<kind_values::override_, kind_values::underride, kind_values::sender, kind_values::room, kind_values::content, std::string>;
  struct body_t {
    std::vector<knot::value> actions;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  kind_t kind;
  std::string rule_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushrules/global/" + percent_encoded(detail::text(kind)) + "/" + percent_encoded(detail::text(rule_id)) + "/actions";
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
