// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec pusher.yaml: do not edit.
export module loom.cs.pusher;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/pushers: Gets the current pushers for the authenticated user
struct get_pushers {
  struct response_t {
    struct pusher_t {
      struct pusher_data_t {
        std::optional<std::string> url;
        std::optional<std::string> format;
        friend consteval auto json_schema(knot::type<pusher_data_t>) { return knot::schema<pusher_data_t>(); }
      };
      std::string pushkey;
      std::string kind;
      std::string app_id;
      std::string app_display_name;
      std::string device_display_name;
      std::optional<std::string> profile_tag;
      std::string lang;
      pusher_data_t data;
      friend consteval auto json_schema(knot::type<pusher_t>) { return knot::schema<pusher_t>(); }
    };
    std::optional<std::vector<pusher_t>> pushers;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushers";
    return {method::get{}, std::move(target), "", true};
  }
};

// POST /_matrix/client/v3/pushers/set: Modify a pusher for this user on the homeserver.
struct post_pusher {
  struct body_t {
    struct pusher_data_t {
      struct format_values {
        struct event_id_only {
          static constexpr std::string_view json_value = "event_id_only";
          friend constexpr bool operator==(event_id_only, event_id_only) = default;
        };
      };
      using format_t = std::variant<format_values::event_id_only, std::string>;
      std::optional<std::string> url;
      std::optional<format_t> format;
      friend consteval auto json_schema(knot::type<pusher_data_t>) { return knot::schema<pusher_data_t>(); }
    };
    std::string pushkey;
    std::string kind;
    std::string app_id;
    std::optional<std::string> app_display_name;
    std::optional<std::string> device_display_name;
    std::optional<std::string> profile_tag;
    std::optional<std::string> lang;
    std::optional<pusher_data_t> data;
    std::optional<bool> append;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/pushers/set";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
