// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec read_markers.yaml: do not edit.
export module loom.cs.read_markers;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/rooms/{roomId}/read_markers: Set the position of the read marker for a room.
struct set_read_marker {
  struct body_t {
    std::optional<std::string> m_fully_read;
    std::optional<std::string> m_read;
    std::optional<std::string> m_read_private;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"m_fully_read">(knot::key("m.fully_read")).member<"m_read">(knot::key("m.read")).member<"m_read_private">(knot::key("m.read.private")); }
  };
  std::string room_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/read_markers";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
