// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec redaction.yaml: do not edit.
export module loom.cs.redaction;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// PUT /_matrix/client/v3/rooms/{roomId}/redact/{eventId}/{txnId}: Strips all non-integrity-critical information out of an event.
struct redact_event {
  struct body_t {
    std::optional<std::string> reason;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    std::optional<std::string> event_id;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  std::string event_id;
  std::string txn_id;
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/redact/" + percent_encoded(detail::text(event_id)) + "/" + percent_encoded(detail::text(txn_id));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
