// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec refresh.yaml: do not edit.
export module loom.cs.refresh;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/refresh: Refresh an access token
struct refresh {
  struct body_t {
    std::string refresh_token;
    knot::value rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    std::string access_token;
    std::optional<std::string> refresh_token;
    std::optional<std::int64_t> expires_in_ms;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/refresh";
    return {method::post{}, std::move(target), detail::json(body), false};
  }
};
}  // namespace loom::cs
