// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec registration_tokens.yaml: do not edit.
export module loom.cs.registration_tokens;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/register/m.login.registration_token/validity: Query if a given registration token is still valid.
struct registration_token_validity {
  struct response_t {
    bool valid;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string token;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/register/m.login.registration_token/validity";
    detail::query(target, "token", detail::text(token));
    return {method::get{}, std::move(target), "", false};
  }
};
}  // namespace loom::cs
