// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec registration.yaml: do not edit.
export module loom.cs.registration;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/register: Register for an account on this homeserver.
struct register_ {
  struct kind_values {
    struct guest {
      static constexpr std::string_view json_value = "guest";
      friend constexpr bool operator==(guest, guest) = default;
    };
    struct user {
      static constexpr std::string_view json_value = "user";
      friend constexpr bool operator==(user, user) = default;
    };
  };
  using kind_t = splice::variant<kind_values::guest, kind_values::user, std::string>;
  struct body_t {
    struct authentication_data_t {
      std::optional<std::string> type;
      std::optional<std::string> session;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<authentication_data_t>) { return knot::schema<authentication_data_t>().member<"rest">(knot::rest); }
    };
    std::optional<authentication_data_t> auth;
    std::optional<std::string> username;
    std::optional<std::string> password;
    std::optional<std::string> device_id;
    std::optional<std::string> initial_device_display_name;
    std::optional<bool> inhibit_login;
    std::optional<bool> refresh_token;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  struct response_t {
    std::string user_id;
    std::optional<std::string> access_token;
    std::optional<std::string> refresh_token;
    std::optional<std::int64_t> expires_in_ms;
    std::optional<std::string> home_server;
    std::optional<std::string> device_id;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::optional<kind_t> kind;
  body_t body;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/register";
    if (kind)
      detail::query(target, "kind", detail::text((*kind)));
    return {method::post{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/register/email/requestToken: Begins the validation process for an email to be used during registration.
struct request_token_to_register_email {
  def::request_email_validation_t body;
  using response = def::request_token_response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/register/email/requestToken";
    return {method::post{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// POST /_matrix/client/v3/register/msisdn/requestToken: Requests a validation token be sent to the given phone number for the purpose of registering an account
struct request_token_to_register_msisdn {
  def::request_msisdn_validation_t body;
  using response = def::request_token_response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/register/msisdn/requestToken";
    return {method::post{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};

// GET /_matrix/client/v3/register/available: Checks to see if a username is available on the server.
struct check_username_availability {
  struct response_t {
    std::optional<bool> available;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string username;
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/register/available";
    detail::query(target, "username", detail::text(username));
    return {method::get{}, std::move(target), false, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
