// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec relations.yaml: do not edit.
export module loom.cs.relations;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/rooms/{roomId}/relations/{eventId}: Get the child events for a given parent event.
struct get_relating_events {
  struct dir_values {
    struct b {
      static constexpr std::string_view json_value = "b";
      friend constexpr bool operator==(b, b) = default;
    };
    struct f {
      static constexpr std::string_view json_value = "f";
      friend constexpr bool operator==(f, f) = default;
    };
  };
  using dir_t = std::variant<dir_values::b, dir_values::f, std::string>;
  struct response_t {
    std::optional<std::string> next_batch;
    std::optional<std::string> prev_batch;
    std::optional<std::int64_t> recursion_depth;
    std::vector<loom::ev::timeline_event> chunk;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  std::string event_id;
  std::optional<std::string> from;
  std::optional<std::string> to;
  std::optional<std::int64_t> limit;
  std::optional<dir_t> dir;
  std::optional<bool> recurse;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/relations/" + percent_encoded(detail::text(event_id));
    if (from)
      detail::query(target, "from", detail::text((*from)));
    if (to)
      detail::query(target, "to", detail::text((*to)));
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (dir)
      detail::query(target, "dir", detail::text((*dir)));
    if (recurse)
      detail::query(target, "recurse", detail::text((*recurse)));
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v1/rooms/{roomId}/relations/{eventId}/{relType}: Get the child events for a given parent event, with a given `relType`.
struct get_relating_events_with_rel_type {
  struct dir_values {
    struct b {
      static constexpr std::string_view json_value = "b";
      friend constexpr bool operator==(b, b) = default;
    };
    struct f {
      static constexpr std::string_view json_value = "f";
      friend constexpr bool operator==(f, f) = default;
    };
  };
  using dir_t = std::variant<dir_values::b, dir_values::f, std::string>;
  struct response_t {
    std::optional<std::string> next_batch;
    std::optional<std::string> prev_batch;
    std::optional<std::int64_t> recursion_depth;
    std::vector<loom::ev::timeline_event> chunk;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  std::string event_id;
  std::string rel_type;
  std::optional<std::string> from;
  std::optional<std::string> to;
  std::optional<std::int64_t> limit;
  std::optional<dir_t> dir;
  std::optional<bool> recurse;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/relations/" + percent_encoded(detail::text(event_id)) + "/" + percent_encoded(detail::text(rel_type));
    if (from)
      detail::query(target, "from", detail::text((*from)));
    if (to)
      detail::query(target, "to", detail::text((*to)));
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (dir)
      detail::query(target, "dir", detail::text((*dir)));
    if (recurse)
      detail::query(target, "recurse", detail::text((*recurse)));
    return {method::get{}, std::move(target), "", true};
  }
};

// GET /_matrix/client/v1/rooms/{roomId}/relations/{eventId}/{relType}/{eventType}: Get the child events for a given parent event, with a given `relType` and `eventType`.
struct get_relating_events_with_rel_type_and_event_type {
  struct dir_values {
    struct b {
      static constexpr std::string_view json_value = "b";
      friend constexpr bool operator==(b, b) = default;
    };
    struct f {
      static constexpr std::string_view json_value = "f";
      friend constexpr bool operator==(f, f) = default;
    };
  };
  using dir_t = std::variant<dir_values::b, dir_values::f, std::string>;
  struct response_t {
    std::optional<std::string> next_batch;
    std::optional<std::string> prev_batch;
    std::optional<std::int64_t> recursion_depth;
    std::vector<loom::ev::timeline_event> chunk;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  std::string event_id;
  std::string rel_type;
  std::string event_type;
  std::optional<std::string> from;
  std::optional<std::string> to;
  std::optional<std::int64_t> limit;
  std::optional<dir_t> dir;
  std::optional<bool> recurse;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/relations/" + percent_encoded(detail::text(event_id)) + "/" + percent_encoded(detail::text(rel_type)) + "/" + percent_encoded(detail::text(event_type));
    if (from)
      detail::query(target, "from", detail::text((*from)));
    if (to)
      detail::query(target, "to", detail::text((*to)));
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (dir)
      detail::query(target, "dir", detail::text((*dir)));
    if (recurse)
      detail::query(target, "recurse", detail::text((*recurse)));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
