// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec report_content.yaml: do not edit.
export module loom.cs.report_content;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/rooms/{roomId}/report: Report a room as inappropriate.
struct report_room {
  struct body_t {
    std::string reason;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  std::string room_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/report";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/rooms/{roomId}/report/{eventId}: Report an event in a joined room as inappropriate.
struct report_event {
  struct body_t {
    std::optional<std::string> reason;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  std::string room_id;
  std::string event_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/report/" + percent_encoded(detail::text(event_id));
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};

// POST /_matrix/client/v3/users/{userId}/report: Report a user as inappropriate.
struct report_user {
  struct body_t {
    std::string reason;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  std::string user_id;
  body_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/users/" + percent_encoded(detail::text(user_id)) + "/report";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
