// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec room_state.yaml: do not edit.
export module loom.cs.room_state;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// PUT /_matrix/client/v3/rooms/{roomId}/state/{eventType}/{stateKey}: Send a state event to the given room.
struct set_room_state_with_key {
  struct response_t {
    std::string event_id;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  std::string event_type;
  std::string state_key;
  knot::value body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/state/" + percent_encoded(detail::text(event_type)) + "/" + percent_encoded(detail::text(state_key));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
