// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec room_event_by_timestamp.yaml: do not edit.
export module loom.cs.room_event_by_timestamp;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/rooms/{roomId}/timestamp_to_event: Get the closest event ID to the given timestamp
struct get_event_by_timestamp {
  struct dir_values {
    struct f {
      static constexpr std::string_view json_value = "f";
      friend constexpr bool operator==(f, f) = default;
    };
    struct b {
      static constexpr std::string_view json_value = "b";
      friend constexpr bool operator==(b, b) = default;
    };
  };
  using dir_t = std::variant<dir_values::f, dir_values::b, std::string>;
  struct response_t {
    std::string event_id;
    std::int64_t origin_server_ts;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  std::int64_t ts;
  dir_t dir;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/timestamp_to_event";
    detail::query(target, "ts", detail::text(ts));
    detail::query(target, "dir", detail::text(dir));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
