// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec room_summary.yaml: do not edit.
export module loom.cs.room_summary;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/room_summary/{roomIdOrAlias}: Retrieves a summary for a room.
struct get_room_summary {
  struct room_summary_t {
    struct encryption_values {
      struct m_megolm_v1_aes_sha2 {
        static constexpr std::string_view json_value = "m.megolm.v1.aes-sha2";
        friend constexpr bool operator==(m_megolm_v1_aes_sha2, m_megolm_v1_aes_sha2) = default;
      };
    };
    using encryption_t = std::variant<encryption_values::m_megolm_v1_aes_sha2, std::string>;
    struct membership_values {
      struct invite {
        static constexpr std::string_view json_value = "invite";
        friend constexpr bool operator==(invite, invite) = default;
      };
      struct join {
        static constexpr std::string_view json_value = "join";
        friend constexpr bool operator==(join, join) = default;
      };
      struct knock {
        static constexpr std::string_view json_value = "knock";
        friend constexpr bool operator==(knock, knock) = default;
      };
      struct leave {
        static constexpr std::string_view json_value = "leave";
        friend constexpr bool operator==(leave, leave) = default;
      };
      struct ban {
        static constexpr std::string_view json_value = "ban";
        friend constexpr bool operator==(ban, ban) = default;
      };
    };
    using membership_t = std::variant<membership_values::invite, membership_values::join, membership_values::knock, membership_values::leave, membership_values::ban, std::string>;
    std::optional<std::string> canonical_alias;
    std::optional<std::string> name;
    std::int64_t num_joined_members;
    std::string room_id;
    std::optional<std::string> topic;
    bool world_readable;
    bool guest_can_join;
    std::optional<std::string> avatar_url;
    std::optional<std::string> join_rule;
    std::optional<std::string> room_type;
    std::optional<std::vector<std::string>> allowed_room_ids;
    std::optional<encryption_t> encryption;
    std::optional<std::string> room_version;
    std::optional<membership_t> membership;
    knot::value rest;
    friend consteval auto json_schema(knot::type<room_summary_t>) { return knot::schema<room_summary_t>().member<"rest">(knot::rest); }
  };
  std::string room_id_or_alias;
  std::optional<std::vector<std::string>> via;
  using response = room_summary_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/room_summary/" + percent_encoded(detail::text(room_id_or_alias));
    if (via)
      for (const auto& one : (*via)) detail::query(target, "via", detail::text(one));
    return {method::get{}, std::move(target), "", false};
  }
};
}  // namespace loom::cs
