// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec room_initial_sync.yaml: do not edit.
export module loom.cs.room_initial_sync;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/rooms/{roomId}/initialSync: Snapshot the current state of a room and its most recent messages.
struct room_initial_sync {
  struct room_info_t {
    struct membership_values {
      struct invite {
        static constexpr std::string_view json_value = "invite";
        friend constexpr bool operator==(invite, invite) = default;
      };
      struct join {
        static constexpr std::string_view json_value = "join";
        friend constexpr bool operator==(join, join) = default;
      };
      struct leave {
        static constexpr std::string_view json_value = "leave";
        friend constexpr bool operator==(leave, leave) = default;
      };
      struct ban {
        static constexpr std::string_view json_value = "ban";
        friend constexpr bool operator==(ban, ban) = default;
      };
    };
    using membership_t = std::variant<membership_values::invite, membership_values::join, membership_values::leave, membership_values::ban, std::string>;
    struct pagination_chunk_t {
      std::optional<std::string> start;
      std::string end;
      std::vector<loom::ev::timeline_event> chunk;
      knot::value rest;
      friend consteval auto json_schema(knot::type<pagination_chunk_t>) { return knot::schema<pagination_chunk_t>().member<"rest">(knot::rest); }
    };
    struct visibility_values {
      struct private_ {
        static constexpr std::string_view json_value = "private";
        friend constexpr bool operator==(private_, private_) = default;
      };
      struct public_ {
        static constexpr std::string_view json_value = "public";
        friend constexpr bool operator==(public_, public_) = default;
      };
    };
    using visibility_t = std::variant<visibility_values::private_, visibility_values::public_, std::string>;
    struct event_t {
      knot::value content;
      std::string type;
      knot::value rest;
      friend consteval auto json_schema(knot::type<event_t>) { return knot::schema<event_t>().member<"rest">(knot::rest); }
    };
    std::string room_id;
    std::optional<membership_t> membership;
    std::optional<pagination_chunk_t> messages;
    std::optional<std::vector<loom::ev::timeline_event>> state;
    std::optional<visibility_t> visibility;
    std::optional<std::vector<event_t>> account_data;
    knot::value rest;
    friend consteval auto json_schema(knot::type<room_info_t>) { return knot::schema<room_info_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  using response = room_info_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/initialSync";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
