// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec room_send.yaml: do not edit.
export module loom.cs.room_send;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// PUT /_matrix/client/v3/rooms/{roomId}/send/{eventType}/{txnId}: Send a message event to the given room.
struct send_message {
  struct response_t {
    std::string event_id;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  std::string event_type;
  std::string txn_id;
  knot::value body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/send/" + percent_encoded(detail::text(event_type)) + "/" + percent_encoded(detail::text(txn_id));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
