// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec room_upgrades.yaml: do not edit.
export module loom.cs.room_upgrades;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/rooms/{roomId}/upgrade: Upgrades a room to a new room version.
struct upgrade_room {
  struct body_t {
    std::string new_version;
    std::optional<std::vector<std::string>> additional_creators;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct response_t {
    std::string replacement_room;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  std::string room_id;
  body_t body;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/upgrade";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
