// Generated by tools/generate.py from matrix-spec search.yaml: do not edit.
export module loom.cs.search;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/search: Perform a server-side search.
struct search {
  struct body_t {
    struct categories_t {
      struct room_events_criteria_t {
        struct keys_item_values {
          struct content_body {
            static constexpr std::string_view json_value = "content.body";
            friend constexpr bool operator==(content_body, content_body) = default;
          };
          struct content_name {
            static constexpr std::string_view json_value = "content.name";
            friend constexpr bool operator==(content_name, content_name) = default;
          };
          struct content_topic {
            static constexpr std::string_view json_value = "content.topic";
            friend constexpr bool operator==(content_topic, content_topic) = default;
          };
        };
        using keys_item_t = std::variant<keys_item_values::content_body, keys_item_values::content_name, keys_item_values::content_topic, std::string>;
        struct filter_t {
          std::optional<std::int64_t> limit;
          std::optional<std::vector<std::string>> not_senders;
          std::optional<std::vector<std::string>> not_types;
          std::optional<std::vector<std::string>> senders;
          std::optional<std::vector<std::string>> types;
          std::optional<bool> unread_thread_notifications;
          std::optional<bool> lazy_load_members;
          std::optional<bool> include_redundant_members;
          std::optional<std::vector<std::string>> not_rooms;
          std::optional<std::vector<std::string>> rooms;
          std::optional<bool> contains_url;
          friend consteval auto json_schema(knot::type<filter_t>) { return knot::schema<filter_t>(); }
        };
        struct order_by_values {
          struct recent {
            static constexpr std::string_view json_value = "recent";
            friend constexpr bool operator==(recent, recent) = default;
          };
          struct rank {
            static constexpr std::string_view json_value = "rank";
            friend constexpr bool operator==(rank, rank) = default;
          };
        };
        using order_by_t = std::variant<order_by_values::recent, order_by_values::rank, std::string>;
        struct include_event_context_t {
          std::optional<std::int64_t> before_limit;
          std::optional<std::int64_t> after_limit;
          std::optional<bool> include_profile;
          friend consteval auto json_schema(knot::type<include_event_context_t>) { return knot::schema<include_event_context_t>(); }
        };
        struct groupings_t {
          struct group_t {
            struct key_values {
              struct room_id {
                static constexpr std::string_view json_value = "room_id";
                friend constexpr bool operator==(room_id, room_id) = default;
              };
              struct sender {
                static constexpr std::string_view json_value = "sender";
                friend constexpr bool operator==(sender, sender) = default;
              };
            };
            using key_t = std::variant<key_values::room_id, key_values::sender, std::string>;
            std::optional<key_t> key;
            friend consteval auto json_schema(knot::type<group_t>) { return knot::schema<group_t>(); }
          };
          std::optional<std::vector<group_t>> group_by;
          friend consteval auto json_schema(knot::type<groupings_t>) { return knot::schema<groupings_t>(); }
        };
        std::string search_term;
        std::optional<std::vector<keys_item_t>> keys;
        std::optional<filter_t> filter;
        std::optional<order_by_t> order_by;
        std::optional<include_event_context_t> event_context;
        std::optional<bool> include_state;
        std::optional<groupings_t> groupings;
        friend consteval auto json_schema(knot::type<room_events_criteria_t>) { return knot::schema<room_events_criteria_t>(); }
      };
      std::optional<room_events_criteria_t> room_events;
      friend consteval auto json_schema(knot::type<categories_t>) { return knot::schema<categories_t>(); }
    };
    categories_t search_categories;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>(); }
  };
  struct results_t {
    struct result_categories_t {
      struct result_room_events_t {
        struct result_t {
          struct event_t {
            struct unsigned_t {
              std::optional<knot::value> redacted_because;
              friend consteval auto json_schema(knot::type<unsigned_t>) { return knot::schema<unsigned_t>(); }
            };
            std::string event_id;
            std::string type;
            std::optional<std::string> state_key;
            std::string sender;
            std::int64_t origin_server_ts;
            knot::value content;
            std::optional<unsigned_t> unsigned_;
            std::string room_id;
            friend consteval auto json_schema(knot::type<event_t>) { return knot::schema<event_t>().member<"unsigned_">(knot::key("unsigned")); }
          };
          struct event_context_t {
            struct user_profile_t {
              std::optional<std::string> displayname;
              std::optional<std::string> avatar_url;
              friend consteval auto json_schema(knot::type<user_profile_t>) { return knot::schema<user_profile_t>(); }
            };
            std::optional<std::string> start;
            std::optional<std::string> end;
            std::optional<std::map<std::string, user_profile_t>> profile_info;
            std::optional<std::vector<def::client_event_t>> events_before;
            std::optional<std::vector<def::client_event_t>> events_after;
            friend consteval auto json_schema(knot::type<event_context_t>) { return knot::schema<event_context_t>(); }
          };
          std::optional<double> rank;
          std::optional<event_t> result;
          std::optional<event_context_t> context;
          friend consteval auto json_schema(knot::type<result_t>) { return knot::schema<result_t>(); }
        };
        struct group_value_t {
          std::optional<std::string> next_batch;
          std::optional<std::int64_t> order;
          std::optional<std::vector<std::string>> results;
          friend consteval auto json_schema(knot::type<group_value_t>) { return knot::schema<group_value_t>(); }
        };
        std::optional<std::int64_t> count;
        std::optional<std::vector<std::string>> highlights;
        std::optional<std::vector<result_t>> results;
        std::optional<std::map<std::string, std::vector<def::client_event_t>>> state;
        std::optional<std::map<std::string, std::map<std::string, group_value_t>>> groups;
        std::optional<std::string> next_batch;
        friend consteval auto json_schema(knot::type<result_room_events_t>) { return knot::schema<result_room_events_t>(); }
      };
      std::optional<result_room_events_t> room_events;
      friend consteval auto json_schema(knot::type<result_categories_t>) { return knot::schema<result_categories_t>(); }
    };
    result_categories_t search_categories;
    friend consteval auto json_schema(knot::type<results_t>) { return knot::schema<results_t>(); }
  };
  std::optional<std::string> next_batch;
  body_t body;
  using response = results_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/search";
    if (next_batch)
      detail::query(target, "next_batch", detail::text((*next_batch)));
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
