// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec space_hierarchy.yaml: do not edit.
export module loom.cs.space_hierarchy;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/rooms/{roomId}/hierarchy: Retrieve a portion of a space tree.
struct get_space_hierarchy {
  struct response_t {
    struct room_summary_t {
      struct encryption_values {
        struct m_megolm_v1_aes_sha2 {
          static constexpr std::string_view json_value = "m.megolm.v1.aes-sha2";
          friend constexpr bool operator==(m_megolm_v1_aes_sha2, m_megolm_v1_aes_sha2) = default;
        };
      };
      using encryption_t = splice::variant<encryption_values::m_megolm_v1_aes_sha2, std::string>;
      std::optional<std::string> canonical_alias;
      std::optional<std::string> name;
      std::int64_t num_joined_members;
      std::string room_id;
      std::optional<std::string> topic;
      bool world_readable;
      bool guest_can_join;
      std::optional<std::string> avatar_url;
      std::optional<std::string> join_rule;
      std::optional<std::string> room_type;
      std::optional<std::vector<std::string>> allowed_room_ids;
      std::optional<encryption_t> encryption;
      std::optional<std::string> room_version;
      std::vector<loom::ev::stripped_event<loom::ev::state_content>> children_state;
      knot::raw rest;
      friend consteval auto json_schema(knot::type<room_summary_t>) { return knot::schema<room_summary_t>().member<"rest">(knot::rest); }
    };
    std::vector<room_summary_t> rooms;
    std::optional<std::string> next_batch;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  std::optional<bool> suggested_only;
  std::optional<std::int64_t> limit;
  std::optional<std::int64_t> max_depth;
  std::optional<std::string> from;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/hierarchy";
    if (suggested_only)
      detail::query(target, "suggested_only", detail::text((*suggested_only)));
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (max_depth)
      detail::query(target, "max_depth", detail::text((*max_depth)));
    if (from)
      detail::query(target, "from", detail::text((*from)));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
