// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec sso_login_redirect.yaml: do not edit.
export module loom.cs.sso_login_redirect;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/login/sso/redirect: Redirect the user's browser to the SSO interface.
struct redirect_to_sso {
  struct action_values {
    struct login {
      static constexpr std::string_view json_value = "login";
      friend constexpr bool operator==(login, login) = default;
    };
    struct register_ {
      static constexpr std::string_view json_value = "register";
      friend constexpr bool operator==(register_, register_) = default;
    };
  };
  using action_t = std::variant<action_values::login, action_values::register_, std::string>;
  std::string redirect_url;
  std::optional<action_t> action;
  using response = loom::empty;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/login/sso/redirect";
    detail::query(target, "redirectUrl", detail::text(redirect_url));
    if (action)
      detail::query(target, "action", detail::text((*action)));
    return {method::get{}, std::move(target), "", false};
  }
};

// GET /_matrix/client/v3/login/sso/redirect/{idpId}: Redirect the user's browser to the SSO interface for an IdP.
struct redirect_to_id_p {
  struct action_values {
    struct login {
      static constexpr std::string_view json_value = "login";
      friend constexpr bool operator==(login, login) = default;
    };
    struct register_ {
      static constexpr std::string_view json_value = "register";
      friend constexpr bool operator==(register_, register_) = default;
    };
  };
  using action_t = std::variant<action_values::login, action_values::register_, std::string>;
  std::string idp_id;
  std::string redirect_url;
  std::optional<action_t> action;
  using response = loom::empty;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/login/sso/redirect/" + percent_encoded(detail::text(idp_id));
    detail::query(target, "redirectUrl", detail::text(redirect_url));
    if (action)
      detail::query(target, "action", detail::text((*action)));
    return {method::get{}, std::move(target), "", false};
  }
};
}  // namespace loom::cs
