// Generated by tools/generate.py from matrix-spec support.yaml: do not edit.
export module loom.cs.support;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /.well-known/matrix/support: Gets homeserver contacts and support details.
struct get_wellknown_support {
  struct response_t {
    struct contact_t {
      struct role_values {
        struct m_role_admin {
          static constexpr std::string_view json_value = "m.role.admin";
          friend constexpr bool operator==(m_role_admin, m_role_admin) = default;
        };
        struct m_role_security {
          static constexpr std::string_view json_value = "m.role.security";
          friend constexpr bool operator==(m_role_security, m_role_security) = default;
        };
      };
      using role_t = std::variant<role_values::m_role_admin, role_values::m_role_security, std::string>;
      std::optional<std::string> matrix_id;
      std::optional<std::string> email_address;
      role_t role;
      friend consteval auto json_schema(knot::type<contact_t>) { return knot::schema<contact_t>(); }
    };
    std::optional<std::vector<contact_t>> contacts;
    std::optional<std::string> support_page;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/.well-known") + "/matrix/support";
    return {method::get{}, std::move(target), "", false};
  }
};
}  // namespace loom::cs
