// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec tags.yaml: do not edit.
export module loom.cs.tags;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/user/{userId}/rooms/{roomId}/tags: List the tags for a room.
struct get_room_tags {
  struct response_t {
    std::optional<std::map<std::string, def::tag_t>> tags;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string user_id;
  std::string room_id;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/rooms/" + percent_encoded(detail::text(room_id)) + "/tags";
    return {method::get{}, std::move(target), "", true};
  }
};

// PUT /_matrix/client/v3/user/{userId}/rooms/{roomId}/tags/{tag}: Add a tag to a room.
struct set_room_tag {
  std::string user_id;
  std::string room_id;
  std::string tag;
  def::tag_t body;
  using response = knot::raw;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/rooms/" + percent_encoded(detail::text(room_id)) + "/tags/" + percent_encoded(detail::text(tag));
    return {method::put{}, std::move(target), detail::json(body), true};
  }
};

// DELETE /_matrix/client/v3/user/{userId}/rooms/{roomId}/tags/{tag}: Remove a tag from the room.
struct delete_room_tag {
  std::string user_id;
  std::string room_id;
  std::string tag;
  using response = knot::raw;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/user/" + percent_encoded(detail::text(user_id)) + "/rooms/" + percent_encoded(detail::text(room_id)) + "/tags/" + percent_encoded(detail::text(tag));
    return {method::delete_{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
