// Generated by tools/generate.py from matrix-spec third_party_membership.yaml: do not edit.
export module loom.cs.third_party_membership;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// POST /_matrix/client/v3/rooms/{roomId}/invite: Invite a user to participate in a particular room.
struct invite_by3_pid {
  std::string room_id;
  def::invite3pid_t body;
  using response = knot::value;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/invite";
    return {method::post{}, std::move(target), detail::json(body), true};
  }
};
}  // namespace loom::cs
