// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec threads_list.yaml: do not edit.
export module loom.cs.threads_list;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v1/rooms/{roomId}/threads: Fetches a list of the threads in a room.
struct get_thread_roots {
  struct include_values {
    struct all {
      static constexpr std::string_view json_value = "all";
      friend constexpr bool operator==(all, all) = default;
    };
    struct participated {
      static constexpr std::string_view json_value = "participated";
      friend constexpr bool operator==(participated, participated) = default;
    };
  };
  using include_t = std::variant<include_values::all, include_values::participated, std::string>;
  struct response_t {
    std::vector<loom::ev::timeline_event> chunk;
    std::optional<std::string> next_batch;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  std::string room_id;
  std::optional<include_t> include;
  std::optional<std::int64_t> limit;
  std::optional<std::string> from;
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v1") + "/rooms/" + percent_encoded(detail::text(room_id)) + "/threads";
    if (include)
      detail::query(target, "include", detail::text((*include)));
    if (limit)
      detail::query(target, "limit", detail::text((*limit)));
    if (from)
      detail::query(target, "from", detail::text((*from)));
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
