// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec to_device.yaml: do not edit.
export module loom.cs.to_device;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// PUT /_matrix/client/v3/sendToDevice/{eventType}/{txnId}: Send an event to a given set of devices.
struct send_to_device {
  struct body_t {
    std::map<std::string, std::map<std::string, knot::raw>> messages;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<body_t>) { return knot::schema<body_t>().member<"rest">(knot::rest); }
  };
  std::string event_type;
  std::string txn_id;
  body_t body;
  using response = knot::raw;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client/v3") + "/sendToDevice/" + percent_encoded(detail::text(event_type)) + "/" + percent_encoded(detail::text(txn_id));
    return {method::put{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    knot::write_chunks(std::forward<Sink>(sink), body);
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
