// Generated by tools/generate.py from matrix-spec versions.yaml: do not edit.
export module loom.cs.versions;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/versions: Gets the versions of the specification supported by the server.
struct get_versions {
  struct response_t {
    std::vector<std::string> versions;
    std::optional<std::map<std::string, bool>> unstable_features;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client") + "/versions";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
