// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec versions.yaml: do not edit.
export module loom.cs.versions;

import std;
export import splice;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/versions: Gets the versions of the specification supported by the server.
struct get_versions {
  struct response_t {
    std::vector<std::string> versions;
    std::optional<std::map<std::string, bool>> unstable_features;
    knot::raw rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request_head to_head() const {
    std::string target = std::string("/_matrix/client") + "/versions";
    return {method::get{}, std::move(target), true, "application/json"};
  }
  template <class Sink>
  constexpr void write_body(Sink&& sink) const {
    (void)sink;
  }
  constexpr request to_send() const { return detail::collect_request(*this); }
};
}  // namespace loom::cs
