// Generated by tools/generate.py from matrix-spec voip.yaml: do not edit.
export module loom.cs.voip;

import std;
export import knot;
export import loom.api;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/voip/turnServer: Obtain TURN server credentials.
struct get_turn_server {
  struct response_t {
    std::string username;
    std::string password;
    std::vector<std::string> uris;
    std::int64_t ttl;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>(); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/voip/turnServer";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
