// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py from matrix-spec whoami.yaml: do not edit.
export module loom.cs.whoami;

import std;
export import knot;
export import loom.api;
export import loom.ev;
export import loom.cs.definitions;

export namespace loom::cs {

// GET /_matrix/client/v3/account/whoami: Gets information about the owner of an access token.
struct get_token_owner {
  struct response_t {
    std::string user_id;
    std::optional<std::string> device_id;
    std::optional<bool> is_guest;
    knot::value rest;
    friend consteval auto json_schema(knot::type<response_t>) { return knot::schema<response_t>().member<"rest">(knot::rest); }
  };
  using response = response_t;
  constexpr request to_send() const {
    std::string target = std::string("/_matrix/client/v3") + "/account/whoami";
    return {method::get{}, std::move(target), "", true};
  }
};
}  // namespace loom::cs
