// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py from matrix-spec data/event-schemas: do not edit.
// Every event the specification defines: its content as a type, tagged with its event
// type, and the unions events are read into.
export module loom.ev;

import std;
export import knot;

export namespace loom::ev {

namespace def {



}  // namespace def

struct m_accepted_terms_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_accepted_terms_content_t>) { return knot::schema<m_accepted_terms_content_t>().member<"rest">(knot::rest).tag("m.accepted_terms"); }
};
struct m_call_answer_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_call_answer_content_t>) { return knot::schema<m_call_answer_content_t>().member<"rest">(knot::rest).tag("m.call.answer"); }
};
struct m_call_candidates_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_call_candidates_content_t>) { return knot::schema<m_call_candidates_content_t>().member<"rest">(knot::rest).tag("m.call.candidates"); }
};
struct m_call_hangup_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_call_hangup_content_t>) { return knot::schema<m_call_hangup_content_t>().member<"rest">(knot::rest).tag("m.call.hangup"); }
};
struct m_call_invite_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_call_invite_content_t>) { return knot::schema<m_call_invite_content_t>().member<"rest">(knot::rest).tag("m.call.invite"); }
};
struct m_call_negotiate_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_call_negotiate_content_t>) { return knot::schema<m_call_negotiate_content_t>().member<"rest">(knot::rest).tag("m.call.negotiate"); }
};
struct m_call_reject_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_call_reject_content_t>) { return knot::schema<m_call_reject_content_t>().member<"rest">(knot::rest).tag("m.call.reject"); }
};
struct m_call_sdp_stream_metadata_changed_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_call_sdp_stream_metadata_changed_content_t>) { return knot::schema<m_call_sdp_stream_metadata_changed_content_t>().member<"rest">(knot::rest).tag("m.call.sdp_stream_metadata_changed"); }
};
struct m_call_select_answer_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_call_select_answer_content_t>) { return knot::schema<m_call_select_answer_content_t>().member<"rest">(knot::rest).tag("m.call.select_answer"); }
};
struct m_direct_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_direct_content_t>) { return knot::schema<m_direct_content_t>().member<"rest">(knot::rest).tag("m.direct"); }
};
struct m_dummy_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_dummy_content_t>) { return knot::schema<m_dummy_content_t>().member<"rest">(knot::rest).tag("m.dummy"); }
};
struct m_forwarded_room_key_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_forwarded_room_key_content_t>) { return knot::schema<m_forwarded_room_key_content_t>().member<"rest">(knot::rest).tag("m.forwarded_room_key"); }
};
struct m_fully_read_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_fully_read_content_t>) { return knot::schema<m_fully_read_content_t>().member<"rest">(knot::rest).tag("m.fully_read"); }
};
struct m_identity_server_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_identity_server_content_t>) { return knot::schema<m_identity_server_content_t>().member<"rest">(knot::rest).tag("m.identity_server"); }
};
struct m_ignored_user_list_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_ignored_user_list_content_t>) { return knot::schema<m_ignored_user_list_content_t>().member<"rest">(knot::rest).tag("m.ignored_user_list"); }
};
struct m_image_pack_rooms_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_image_pack_rooms_content_t>) { return knot::schema<m_image_pack_rooms_content_t>().member<"rest">(knot::rest).tag("m.image_pack.rooms"); }
};
struct m_invite_permission_config_content_t {
  std::optional<std::string> default_action;
  friend consteval auto json_schema(knot::type<m_invite_permission_config_content_t>) { return knot::schema<m_invite_permission_config_content_t>().tag("m.invite_permission_config"); }
};
struct m_key_verification_accept_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_accept_content_t>) { return knot::schema<m_key_verification_accept_content_t>().member<"rest">(knot::rest).tag("m.key.verification.accept"); }
};
struct m_key_verification_cancel_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_cancel_content_t>) { return knot::schema<m_key_verification_cancel_content_t>().member<"rest">(knot::rest).tag("m.key.verification.cancel"); }
};
struct m_key_verification_done_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_done_content_t>) { return knot::schema<m_key_verification_done_content_t>().member<"rest">(knot::rest).tag("m.key.verification.done"); }
};
struct m_key_verification_key_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_key_content_t>) { return knot::schema<m_key_verification_key_content_t>().member<"rest">(knot::rest).tag("m.key.verification.key"); }
};
struct m_key_verification_mac_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_mac_content_t>) { return knot::schema<m_key_verification_mac_content_t>().member<"rest">(knot::rest).tag("m.key.verification.mac"); }
};
struct m_key_verification_ready_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_ready_content_t>) { return knot::schema<m_key_verification_ready_content_t>().member<"rest">(knot::rest).tag("m.key.verification.ready"); }
};
struct m_key_verification_request_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_request_content_t>) { return knot::schema<m_key_verification_request_content_t>().member<"rest">(knot::rest).tag("m.key.verification.request"); }
};
struct m_key_verification_start_m_reciprocate_v1_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_start_m_reciprocate_v1_content_t>) { return knot::schema<m_key_verification_start_m_reciprocate_v1_content_t>().member<"rest">(knot::rest); }
};
struct m_key_verification_start_m_sas_v1_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_start_m_sas_v1_content_t>) { return knot::schema<m_key_verification_start_m_sas_v1_content_t>().member<"rest">(knot::rest); }
};
struct m_key_verification_start_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_verification_start_content_t>) { return knot::schema<m_key_verification_start_content_t>().member<"rest">(knot::rest).tag("m.key.verification.start"); }
};
struct m_key_backup_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_key_backup_content_t>) { return knot::schema<m_key_backup_content_t>().member<"rest">(knot::rest).tag("m.key_backup"); }
};
struct m_marked_unread_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_marked_unread_content_t>) { return knot::schema<m_marked_unread_content_t>().member<"rest">(knot::rest).tag("m.marked_unread"); }
};
struct m_policy_rule_room_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_policy_rule_room_content_t>) { return knot::schema<m_policy_rule_room_content_t>().member<"rest">(knot::rest).tag("m.policy.rule.room"); }
};
struct m_policy_rule_server_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_policy_rule_server_content_t>) { return knot::schema<m_policy_rule_server_content_t>().member<"rest">(knot::rest).tag("m.policy.rule.server"); }
};
struct m_policy_rule_user_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_policy_rule_user_content_t>) { return knot::schema<m_policy_rule_user_content_t>().member<"rest">(knot::rest).tag("m.policy.rule.user"); }
};
struct m_presence_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_presence_content_t>) { return knot::schema<m_presence_content_t>().member<"rest">(knot::rest).tag("m.presence"); }
};
struct m_push_rules_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_push_rules_content_t>) { return knot::schema<m_push_rules_content_t>().member<"rest">(knot::rest).tag("m.push_rules"); }
};
struct m_reaction_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_reaction_content_t>) { return knot::schema<m_reaction_content_t>().member<"rest">(knot::rest).tag("m.reaction"); }
};
struct m_receipt_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_receipt_content_t>) { return knot::schema<m_receipt_content_t>().member<"rest">(knot::rest).tag("m.receipt"); }
};
struct m_recent_emoji_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_recent_emoji_content_t>) { return knot::schema<m_recent_emoji_content_t>().member<"rest">(knot::rest).tag("m.recent_emoji"); }
};
struct m_room_avatar_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_avatar_content_t>) { return knot::schema<m_room_avatar_content_t>().member<"rest">(knot::rest).tag("m.room.avatar"); }
};
struct m_room_canonical_alias_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_canonical_alias_content_t>) { return knot::schema<m_room_canonical_alias_content_t>().member<"rest">(knot::rest).tag("m.room.canonical_alias"); }
};
struct m_room_create_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_create_content_t>) { return knot::schema<m_room_create_content_t>().member<"rest">(knot::rest).tag("m.room.create"); }
};
struct m_room_encrypted_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_encrypted_content_t>) { return knot::schema<m_room_encrypted_content_t>().member<"rest">(knot::rest).tag("m.room.encrypted"); }
};
struct m_room_encryption_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_encryption_content_t>) { return knot::schema<m_room_encryption_content_t>().member<"rest">(knot::rest).tag("m.room.encryption"); }
};
struct m_room_guest_access_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_guest_access_content_t>) { return knot::schema<m_room_guest_access_content_t>().member<"rest">(knot::rest).tag("m.room.guest_access"); }
};
struct m_room_history_visibility_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_history_visibility_content_t>) { return knot::schema<m_room_history_visibility_content_t>().member<"rest">(knot::rest).tag("m.room.history_visibility"); }
};
struct m_room_image_pack_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_image_pack_content_t>) { return knot::schema<m_room_image_pack_content_t>().member<"rest">(knot::rest).tag("m.room.image_pack"); }
};
struct m_room_join_rules_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_join_rules_content_t>) { return knot::schema<m_room_join_rules_content_t>().member<"rest">(knot::rest).tag("m.room.join_rules"); }
};
struct m_room_member_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_member_content_t>) { return knot::schema<m_room_member_content_t>().member<"rest">(knot::rest).tag("m.room.member"); }
};
struct m_room_message_m_audio_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_audio_content_t>) { return knot::schema<m_room_message_m_audio_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_emote_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_emote_content_t>) { return knot::schema<m_room_message_m_emote_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_file_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_file_content_t>) { return knot::schema<m_room_message_m_file_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_image_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_image_content_t>) { return knot::schema<m_room_message_m_image_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_key_verification_request_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_key_verification_request_content_t>) { return knot::schema<m_room_message_m_key_verification_request_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_location_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_location_content_t>) { return knot::schema<m_room_message_m_location_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_notice_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_notice_content_t>) { return knot::schema<m_room_message_m_notice_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_server_notice_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_server_notice_content_t>) { return knot::schema<m_room_message_m_server_notice_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_text_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_text_content_t>) { return knot::schema<m_room_message_m_text_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_m_video_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_m_video_content_t>) { return knot::schema<m_room_message_m_video_content_t>().member<"rest">(knot::rest); }
};
struct m_room_message_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_message_content_t>) { return knot::schema<m_room_message_content_t>().member<"rest">(knot::rest).tag("m.room.message"); }
};
struct m_room_name_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_name_content_t>) { return knot::schema<m_room_name_content_t>().member<"rest">(knot::rest).tag("m.room.name"); }
};
struct m_room_pinned_events_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_pinned_events_content_t>) { return knot::schema<m_room_pinned_events_content_t>().member<"rest">(knot::rest).tag("m.room.pinned_events"); }
};
struct m_room_policy_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_policy_content_t>) { return knot::schema<m_room_policy_content_t>().member<"rest">(knot::rest).tag("m.room.policy"); }
};
struct m_room_power_levels_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_power_levels_content_t>) { return knot::schema<m_room_power_levels_content_t>().member<"rest">(knot::rest).tag("m.room.power_levels"); }
};
struct m_room_redaction_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_redaction_content_t>) { return knot::schema<m_room_redaction_content_t>().member<"rest">(knot::rest).tag("m.room.redaction"); }
};
struct m_room_server_acl_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_server_acl_content_t>) { return knot::schema<m_room_server_acl_content_t>().member<"rest">(knot::rest).tag("m.room.server_acl"); }
};
struct m_room_third_party_invite_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_third_party_invite_content_t>) { return knot::schema<m_room_third_party_invite_content_t>().member<"rest">(knot::rest).tag("m.room.third_party_invite"); }
};
struct m_room_tombstone_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_tombstone_content_t>) { return knot::schema<m_room_tombstone_content_t>().member<"rest">(knot::rest).tag("m.room.tombstone"); }
};
struct m_room_topic_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_topic_content_t>) { return knot::schema<m_room_topic_content_t>().member<"rest">(knot::rest).tag("m.room.topic"); }
};
struct m_room_key_withheld_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_key_withheld_content_t>) { return knot::schema<m_room_key_withheld_content_t>().member<"rest">(knot::rest).tag("m.room_key.withheld"); }
};
struct m_room_key_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_key_content_t>) { return knot::schema<m_room_key_content_t>().member<"rest">(knot::rest).tag("m.room_key"); }
};
struct m_room_key_bundle_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_key_bundle_content_t>) { return knot::schema<m_room_key_bundle_content_t>().member<"rest">(knot::rest).tag("m.room_key_bundle"); }
};
struct m_room_key_request_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_room_key_request_content_t>) { return knot::schema<m_room_key_request_content_t>().member<"rest">(knot::rest).tag("m.room_key_request"); }
};
struct m_secret_request_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_secret_request_content_t>) { return knot::schema<m_secret_request_content_t>().member<"rest">(knot::rest).tag("m.secret.request"); }
};
struct m_secret_send_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_secret_send_content_t>) { return knot::schema<m_secret_send_content_t>().member<"rest">(knot::rest).tag("m.secret.send"); }
};
struct m_space_child_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_space_child_content_t>) { return knot::schema<m_space_child_content_t>().member<"rest">(knot::rest).tag("m.space.child"); }
};
struct m_space_parent_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_space_parent_content_t>) { return knot::schema<m_space_parent_content_t>().member<"rest">(knot::rest).tag("m.space.parent"); }
};
struct m_sticker_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_sticker_content_t>) { return knot::schema<m_sticker_content_t>().member<"rest">(knot::rest).tag("m.sticker"); }
};
struct m_tag_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_tag_content_t>) { return knot::schema<m_tag_content_t>().member<"rest">(knot::rest).tag("m.tag"); }
};
struct m_typing_content_t {
  knot::value rest;
  friend consteval auto json_schema(knot::type<m_typing_content_t>) { return knot::schema<m_typing_content_t>().member<"rest">(knot::rest).tag("m.typing"); }
};

// The content of a state event, by its type. Any other type is kept as knot::value.
using state_content = knot::tagged<"type", m_policy_rule_room_content_t, m_policy_rule_server_content_t, m_policy_rule_user_content_t, m_room_avatar_content_t, m_room_canonical_alias_content_t, m_room_create_content_t, m_room_encryption_content_t, m_room_guest_access_content_t, m_room_history_visibility_content_t, m_room_image_pack_content_t, m_room_join_rules_content_t, m_room_member_content_t, m_room_name_content_t, m_room_pinned_events_content_t, m_room_policy_content_t, m_room_power_levels_content_t, m_room_server_acl_content_t, m_room_third_party_invite_content_t, m_room_tombstone_content_t, m_room_topic_content_t, m_space_child_content_t, m_space_parent_content_t, knot::value>;
// The content of a message-like room event, by its type. Any other type is kept as knot::value.
using message_content = knot::tagged<"type", m_call_answer_content_t, m_call_candidates_content_t, m_call_hangup_content_t, m_call_invite_content_t, m_call_negotiate_content_t, m_call_reject_content_t, m_call_sdp_stream_metadata_changed_content_t, m_call_select_answer_content_t, m_reaction_content_t, m_room_message_content_t, m_room_redaction_content_t, m_sticker_content_t, knot::value>;
// The content of any room event -- a timeline holds both kinds. Any other type is kept as knot::value.
using timeline_content = knot::tagged<"type", m_call_answer_content_t, m_call_candidates_content_t, m_call_hangup_content_t, m_call_invite_content_t, m_call_negotiate_content_t, m_call_reject_content_t, m_call_sdp_stream_metadata_changed_content_t, m_call_select_answer_content_t, m_reaction_content_t, m_room_message_content_t, m_room_redaction_content_t, m_sticker_content_t, m_policy_rule_room_content_t, m_policy_rule_server_content_t, m_policy_rule_user_content_t, m_room_avatar_content_t, m_room_canonical_alias_content_t, m_room_create_content_t, m_room_encryption_content_t, m_room_guest_access_content_t, m_room_history_visibility_content_t, m_room_image_pack_content_t, m_room_join_rules_content_t, m_room_member_content_t, m_room_name_content_t, m_room_pinned_events_content_t, m_room_policy_content_t, m_room_power_levels_content_t, m_room_server_acl_content_t, m_room_third_party_invite_content_t, m_room_tombstone_content_t, m_room_topic_content_t, m_space_child_content_t, m_space_parent_content_t, knot::value>;
// The content of an event outside a room's timeline: account data, ephemeral, to-device. Any other type is kept as knot::value.
using other_content = knot::tagged<"type", m_accepted_terms_content_t, m_direct_content_t, m_dummy_content_t, m_forwarded_room_key_content_t, m_fully_read_content_t, m_identity_server_content_t, m_ignored_user_list_content_t, m_image_pack_rooms_content_t, m_invite_permission_config_content_t, m_key_verification_accept_content_t, m_key_verification_cancel_content_t, m_key_verification_done_content_t, m_key_verification_key_content_t, m_key_verification_mac_content_t, m_key_verification_ready_content_t, m_key_verification_request_content_t, m_key_verification_start_content_t, m_key_backup_content_t, m_marked_unread_content_t, m_presence_content_t, m_push_rules_content_t, m_receipt_content_t, m_recent_emoji_content_t, m_room_encrypted_content_t, m_room_key_withheld_content_t, m_room_key_content_t, m_room_key_bundle_content_t, m_room_key_request_content_t, m_secret_request_content_t, m_secret_send_content_t, m_tag_content_t, m_typing_content_t, knot::value>;

// What a room event carries besides its content (the spec's ClientEvent and,
// without room_id, ClientEventWithoutRoomID): state_key where it is state.
template <class Content>
struct room_event {
  Content content;
  std::string event_id;
  std::int64_t origin_server_ts = 0;
  std::optional<std::string> room_id;
  std::string sender;
  std::optional<std::string> state_key;
  std::string type;
  std::optional<knot::value> unsigned_;
  friend consteval auto json_schema(knot::type<room_event>) {
    return knot::schema<room_event>().template member<"unsigned_">(knot::key("unsigned"));
  }
};

// A stripped state event, as invites and knocks give them.
template <class Content>
struct stripped_event {
  Content content;
  std::string sender;
  std::string state_key;
  std::string type;
  friend consteval auto json_schema(knot::type<stripped_event>) { return knot::schema<stripped_event>(); }
};

// An event outside a room: its type and content only.
template <class Content>
struct basic_event {
  Content content;
  std::string type;
  friend consteval auto json_schema(knot::type<basic_event>) { return knot::schema<basic_event>(); }
};

using timeline_event = room_event<timeline_content>;
using state_event = room_event<state_content>;
using account_data_event = basic_event<other_content>;

}  // namespace loom::ev
