// Generated by tools/generate.py: the spec's examples for account_data, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.account_data;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(set_account_data, response_0) {
  const auto got = loom::read<loom::cs::set_account_data>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_account_data_per_room, response_0) {
  const auto got = loom::read<loom::cs::set_account_data_per_room>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
