// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for administrative_contact, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.administrative_contact;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_account3_pi_ds, response_0) {
  const auto got = loom::read<loom::cs::get_account3_pi_ds>(200, R"__json({"threepids":[{"medium":"email","address":"monkey@banana.island","validated_at":1535176800000,"added_at":1535336848756}]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(post3_pi_ds, response_0) {
  const auto got = loom::read<loom::cs::post3_pi_ds>(200, R"__json({"submit_url":"https://example.org/path/to/submitToken"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(add3_pid, response_0) {
  const auto got = loom::read<loom::cs::add3_pid>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(bind3_pid, response_0) {
  const auto got = loom::read<loom::cs::bind3_pid>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
