// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for admin, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.admin;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_who_is, response_0) {
  const auto got = loom::read<loom::cs::get_who_is>(200, R"__json({"user_id":"@peter:rabbit.rocks","devices":{"teapot":{"sessions":[{"connections":[{"ip":"127.0.0.1","last_seen":1411996332123,"user_agent":"curl/7.31.0-DEV"},{"ip":"10.0.0.2","last_seen":1411996332123,"user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36"}]}]}}})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_admin_suspend_user, response_0) {
  const auto got = loom::read<loom::cs::get_admin_suspend_user>(200, R"__json({"suspended":true})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_admin_suspend_user, response_0) {
  const auto got = loom::read<loom::cs::set_admin_suspend_user>(200, R"__json({"suspended":true})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_admin_suspend_user, body_0) {
  const auto got = knot::try_read<decltype(loom::cs::set_admin_suspend_user::body)>(R"__json({"suspended":true})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_admin_lock_user, response_0) {
  const auto got = loom::read<loom::cs::get_admin_lock_user>(200, R"__json({"locked":true})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_admin_lock_user, response_0) {
  const auto got = loom::read<loom::cs::set_admin_lock_user>(200, R"__json({"locked":true})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_admin_lock_user, body_0) {
  const auto got = knot::try_read<decltype(loom::cs::set_admin_lock_user::body)>(R"__json({"locked":true})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
