// Generated by tools/generate.py: the spec's examples for appservice_room_directory, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.appservice_room_directory;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(update_appservice_room_directory_visibility, response_0) {
  const auto got = loom::read<loom::cs::update_appservice_room_directory_visibility>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
