// Generated by tools/generate.py: the spec's examples for authed_content_repo, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.authed_content_repo;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_url_preview_authed, response_0) {
  const auto got = loom::read<loom::cs::get_url_preview_authed>(200, R"__json({"og:title":"Matrix Blog Post","og:description":"This is a really cool blog post from matrix.org","og:image":"mxc://example.com/ascERGshawAWawugaAcauga","og:image:type":"image/png","og:image:height":48,"og:image:width":48,"matrix:image:size":102400})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_config_authed, response_0) {
  const auto got = loom::read<loom::cs::get_config_authed>(200, R"__json({"m.upload.size":50000000})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
