// Generated by tools/generate.py: the spec's examples for capabilities, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.capabilities;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_capabilities, response_0) {
  const auto got = loom::read<loom::cs::get_capabilities>(200, R"__json({"capabilities":{"m.change_password":{"enabled":false},"m.room_versions":{"default":"1","available":{"1":"stable","2":"stable","3":"unstable","test-version":"unstable"}},"com.example.custom.ratelimit":{"max_requests_per_hour":600}}})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
