// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for create_room, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.create_room;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(create_room, response_0) {
  const auto got = loom::read<loom::cs::create_room>(200, R"__json({"room_id":"!sefiuhWgwghwWgh:example.com"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
