// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for device_management, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.device_management;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_devices, response_0) {
  const auto got = loom::read<loom::cs::get_devices>(200, R"__json({"devices":[{"device_id":"QBUAZIFURK","display_name":"android","last_seen_ip":"1.2.3.4","last_seen_ts":1474491775024}]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_device, response_0) {
  const auto got = loom::read<loom::cs::get_device>(200, R"__json({"device_id":"QBUAZIFURK","display_name":"android","last_seen_ip":"1.2.3.4","last_seen_ts":1474491775024})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(update_device, response_0) {
  const auto got = loom::read<loom::cs::update_device>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(delete_device, response_0) {
  const auto got = loom::read<loom::cs::delete_device>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(delete_devices, response_0) {
  const auto got = loom::read<loom::cs::delete_devices>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
