// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for directory, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.directory;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(set_room_alias, response_0) {
  const auto got = loom::read<loom::cs::set_room_alias>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_room_id_by_alias, response_0) {
  const auto got = loom::read<loom::cs::get_room_id_by_alias>(200, R"__json({"room_id":"!abnjk1jdasj98:capuchins.com","servers":["capuchins.com","matrix.org","another.com"]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(delete_room_alias, response_0) {
  const auto got = loom::read<loom::cs::delete_room_alias>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_local_aliases, response_0) {
  const auto got = loom::read<loom::cs::get_local_aliases>(200, R"__json({"aliases":["#somewhere:example.com","#another:example.com","#hat_trick:example.com"]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
