// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for filter, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.filter;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_filter, response_0) {
  const auto got = loom::read<loom::cs::get_filter>(200, R"__json({"room":{"state":{"types":["m.room.*"],"not_rooms":["!726s6s6q:example.com"]},"timeline":{"limit":10,"types":["m.room.message"],"not_rooms":["!726s6s6q:example.com"],"not_senders":["@spam:example.com"]},"ephemeral":{"types":["m.receipt","m.typing"],"not_rooms":["!726s6s6q:example.com"],"not_senders":["@spam:example.com"]}},"presence":{"types":["m.presence"],"not_senders":["@alice:example.com"]},"event_format":"client","event_fields":["type","content","sender"]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
