// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for joining, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.joining;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(join_room_by_id, response_0) {
  const auto got = loom::read<loom::cs::join_room_by_id>(200, R"__json({"room_id":"!d41d8cd:matrix.org"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(join_room, response_0) {
  const auto got = loom::read<loom::cs::join_room>(200, R"__json({"room_id":"!d41d8cd:matrix.org"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
