// Generated by tools/generate.py: the spec's examples for key_backup, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.key_backup;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(put_room_keys_version, response_0) {
  const auto got = loom::read<loom::cs::put_room_keys_version>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
