// Generated by tools/generate.py: the spec's examples for knocking, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.knocking;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(knock_room, response_0) {
  const auto got = loom::read<loom::cs::knock_room>(200, R"__json({"room_id":"!d41d8cd:matrix.org"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
