// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for list_joined_rooms, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.list_joined_rooms;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_joined_rooms, response_0) {
  const auto got = loom::read<loom::cs::get_joined_rooms>(200, R"__json({"joined_rooms":["!foo:example.com"]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
