// Generated by tools/generate.py: the spec's examples for login_token, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.login_token;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(generate_login_token, response_0) {
  const auto got = loom::read<loom::cs::generate_login_token>(200, R"__json({"login_token":"<opaque string>","expires_in_ms":120000})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
