// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for login, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.login;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_login_flows, response_0) {
  const auto got = loom::read<loom::cs::get_login_flows>(200, R"__json({"flows":[{"type":"m.login.password"},{"type":"m.login.token","get_login_token":true}]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(login, response_0) {
  const auto got = loom::read<loom::cs::login>(200, R"__json({"user_id":"@cheeky_monkey:matrix.org","access_token":"abc123","refresh_token":"def456","expires_in_ms":60000,"device_id":"GHTYAJCE","well_known":{"m.homeserver":{"base_url":"https://example.org"},"m.identity_server":{"base_url":"https://id.example.org"}}})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
