// Generated by tools/generate.py: the spec's examples for message_pagination, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.message_pagination;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_room_events, response_0) {
  const auto got = loom::read<loom::cs::get_room_events>(200, R"__json({"start":"t47429-4392820_219380_26003_2265","end":"t47409-4357353_219380_26003_2265","chunk":[{"content":{"body":"This is an example text message","msgtype":"m.text","format":"org.matrix.custom.html","formatted_body":"<b>This is an example text message</b>"},"type":"m.room.message","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:example.com","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}},{"content":{"name":"The room name"},"type":"m.room.name","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:example.com","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"},"state_key":""},{"content":{"body":"Gangnam Style","url":"mxc://example.org/a526eYUSFFxlgbQYZmo442","info":{"thumbnail_url":"mxc://example.org/FHyPlCeYUSFFxlgbQYZmoEoe","thumbnail_info":{"mimetype":"image/jpeg","size":46144,"w":300,"h":300},"w":480,"h":320,"duration":2140786,"size":1563685,"mimetype":"video/mp4"},"msgtype":"m.video"},"type":"m.room.message","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:example.com","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}}]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
