// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for openid, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.openid;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(request_open_id_token, response_0) {
  const auto got = loom::read<loom::cs::request_open_id_token>(200, R"__json({"access_token":"SomeT0kenHere","token_type":"Bearer","matrix_server_name":"example.com","expires_in":3600})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
