// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for peeking_events, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.peeking_events;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(peek_events, response_0) {
  const auto got = loom::read<loom::cs::peek_events>(200, R"__json({"start":"s3456_9_0","end":"s3457_9_0","chunk":[{"content":{"body":"This is an example text message","msgtype":"m.text","format":"org.matrix.custom.html","formatted_body":"<b>This is an example text message</b>"},"type":"m.room.message","event_id":"$143273582443PhrSn:example.org","room_id":"!somewhere:over.the.rainbow","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}}]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
