// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for policy_server, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.policy_server;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_wellknown_policy, response_0) {
  const auto got = loom::read<loom::cs::get_wellknown_policy>(200, R"__json({"public_keys":{"ed25519":"6yhHGKhCiXTSEN2ksjV7kX_N6rBQZ3Xb-M7LlC6NS-s"}})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
