// Generated by tools/generate.py: the spec's examples for presence, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.presence;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(set_presence, response_0) {
  const auto got = loom::read<loom::cs::set_presence>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_presence, response_0) {
  const auto got = loom::read<loom::cs::get_presence>(200, R"__json({"presence":"unavailable","last_active_ago":420845})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
