// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for profile, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.profile;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(set_profile_field, response_0) {
  const auto got = loom::read<loom::cs::set_profile_field>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_profile_field, response_0) {
  const auto got = loom::read<loom::cs::get_profile_field>(200, R"__json({"displayname":"Alice"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(delete_profile_field, response_0) {
  const auto got = loom::read<loom::cs::delete_profile_field>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_user_profile, response_0) {
  const auto got = loom::read<loom::cs::get_user_profile>(200, R"__json({"avatar_url":"mxc://matrix.org/SDGdghriugerRg","displayname":"Alice Margatroid","m.tz":"Europe/London","m.example_field":"custom_value"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
