// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for pushrules, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.pushrules;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_push_rule, response_0) {
  const auto got = loom::read<loom::cs::get_push_rule>(200, R"__json({"actions":[],"pattern":"cake*lie","rule_id":"nocake","enabled":true,"default":false})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(delete_push_rule, response_0) {
  const auto got = loom::read<loom::cs::delete_push_rule>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_push_rule, response_0) {
  const auto got = loom::read<loom::cs::set_push_rule>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(is_push_rule_enabled, response_0) {
  const auto got = loom::read<loom::cs::is_push_rule_enabled>(200, R"__json({"enabled":true})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_push_rule_enabled, response_0) {
  const auto got = loom::read<loom::cs::set_push_rule_enabled>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_push_rule_actions, response_0) {
  const auto got = loom::read<loom::cs::get_push_rule_actions>(200, R"__json({"actions":["notify",{"set_tweak":"sound","value":"bing"}]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_push_rule_actions, response_0) {
  const auto got = loom::read<loom::cs::set_push_rule_actions>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
