// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for pusher, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.pusher;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_pushers, response_0) {
  const auto got = loom::read<loom::cs::get_pushers>(200, R"__json({"pushers":[{"pushkey":"Xp/MzCt8/9DcSNE9cuiaoT5Ac55job3TdLSSmtmYl4A=","kind":"http","app_id":"face.mcapp.appy.prod","app_display_name":"Appy McAppface","device_display_name":"Alice's Phone","profile_tag":"xyz","lang":"en-US","data":{"url":"https://example.com/_matrix/push/v1/notify"}}]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(post_pusher, response_0) {
  const auto got = loom::read<loom::cs::post_pusher>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
