// Generated by tools/generate.py: the spec's examples for receipts, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.receipts;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(post_receipt, response_0) {
  const auto got = loom::read<loom::cs::post_receipt>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
