// Generated by tools/generate.py: the spec's examples for redaction, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.redaction;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(redact_event, response_0) {
  const auto got = loom::read<loom::cs::redact_event>(200, R"__json({"event_id":"$YUwQidLecu:example.com"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
