// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for refresh, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.refresh;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(refresh, response_0) {
  const auto got = loom::read<loom::cs::refresh>(200, R"__json({"access_token":"a_new_token","expires_in_ms":60000,"refresh_token":"another_new_token"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
