// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for registration_tokens, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.registration_tokens;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(registration_token_validity, response_0) {
  const auto got = loom::read<loom::cs::registration_token_validity>(200, R"__json({"valid":true})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
