// Generated by tools/generate.py: the spec's examples for registration, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.registration;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(register_, response_0) {
  const auto got = loom::read<loom::cs::register_>(200, R"__json({"user_id":"@cheeky_monkey:matrix.org","access_token":"abc123","device_id":"GHTYAJCE"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(check_username_availability, response_0) {
  const auto got = loom::read<loom::cs::check_username_availability>(200, R"__json({"available":true})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
