// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for relations, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.relations;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_relating_events, response_0) {
  const auto got = loom::read<loom::cs::get_relating_events>(200, R"__json({"chunk":[{"content":{"m.relates_to":{"rel_type":"org.example.my_relation","event_id":"$asfDuShaf7Gafaw"}},"type":"m.room.message","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:matrix.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}}],"next_batch":"page2_token","prev_batch":"page1_token"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_relating_events_with_rel_type, response_0) {
  const auto got = loom::read<loom::cs::get_relating_events_with_rel_type>(200, R"__json({"chunk":[{"content":{"m.relates_to":{"rel_type":"org.example.my_relation","event_id":"$asfDuShaf7Gafaw"}},"type":"m.room.message","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:matrix.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}}],"next_batch":"page2_token","prev_batch":"page1_token"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_relating_events_with_rel_type_and_event_type, response_0) {
  const auto got = loom::read<loom::cs::get_relating_events_with_rel_type_and_event_type>(200, R"__json({"chunk":[{"content":{"m.relates_to":{"rel_type":"org.example.my_relation","event_id":"$asfDuShaf7Gafaw"}},"type":"m.room.message","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:matrix.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}}],"next_batch":"page2_token","prev_batch":"page1_token"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
