// Generated by tools/generate.py: the spec's examples for report_content, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.report_content;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(report_room, response_0) {
  const auto got = loom::read<loom::cs::report_room>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(report_event, response_0) {
  const auto got = loom::read<loom::cs::report_event>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(report_user, response_0) {
  const auto got = loom::read<loom::cs::report_user>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
