// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for room_summary, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.room_summary;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_room_summary, response_0) {
  const auto got = loom::read<loom::cs::get_room_summary>(200, R"__json({"room_id":"!ol19s:bleecker.street","avatar_url":"mxc://bleecker.street/CHEDDARandBRIE","guest_can_join":false,"name":"CHEESE","num_joined_members":37,"topic":"Tasty tasty cheese","world_readable":true,"join_rule":"public","room_type":"m.space","membership":"invite","encryption":"m.megolm.v1.aes-sha2","room_version":"9001"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
