// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for rooms, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.rooms;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_one_room_event, response_0) {
  const auto got = loom::read<loom::cs::get_one_room_event>(200, R"__json({"content":{"body":"This is an example text message","msgtype":"m.text","format":"org.matrix.custom.html","formatted_body":"<b>This is an example text message</b>"},"type":"m.room.message","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:matrix.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_room_state_with_key, response_0) {
  const auto got = loom::read<loom::cs::get_room_state_with_key>(200, R"__json({"name":"Example room name"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_room_state, response_0) {
  const auto got = loom::read<loom::cs::get_room_state>(200, R"__json([{"content":{"join_rule":"public"},"type":"m.room.join_rules","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:example.com","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"},"state_key":""},{"content":{"membership":"join","avatar_url":"mxc://example.org/SEsfnsuifSDFSSEF","displayname":"Alice Margatroid","reason":"Looking for support"},"type":"m.room.member","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:example.com","sender":"@alice:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"},"state_key":"@alice:example.org"},{"content":{"room_version":"11","m.federate":true,"predecessor":{"event_id":"$something:example.org","room_id":"!oldroom:example.org"}},"type":"m.room.create","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:example.com","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"},"state_key":""},{"content":{"ban":50,"events":{"m.room.name":100,"m.room.power_levels":100},"events_default":0,"invite":50,"kick":50,"redact":50,"state_default":50,"users":{"@example:localhost":100},"users_default":0,"notifications":{"room":20}},"type":"m.room.power_levels","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:example.com","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"},"state_key":""}])__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_members_by_room, response_0) {
  const auto got = loom::read<loom::cs::get_members_by_room>(200, R"__json({"chunk":[{"content":{"membership":"join","avatar_url":"mxc://example.org/SEsfnsuifSDFSSEF","displayname":"Alice Margatroid","reason":"Looking for support"},"type":"m.room.member","event_id":"$143273582443PhrSn:example.org","room_id":"!636q39766251:example.com","sender":"@alice:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"},"state_key":"@alice:example.org"}]})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(get_joined_members_by_room, response_0) {
  const auto got = loom::read<loom::cs::get_joined_members_by_room>(200, R"__json({"joined":{"@bar:example.com":{"display_name":"Bar","avatar_url":"mxc://riot.ovh/printErCATzZijQsSDWorRaK"}}})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
