// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for room_send, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.room_send;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(send_message, response_0) {
  const auto got = loom::read<loom::cs::send_message>(200, R"__json({"event_id":"$YUwRidLecu:example.com"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
