// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for room_event_by_timestamp, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.room_event_by_timestamp;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_event_by_timestamp, response_0) {
  const auto got = loom::read<loom::cs::get_event_by_timestamp>(200, R"__json({"event_id":"$143273582443PhrSn:example.org","origin_server_ts":1432735824653})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
