// Generated by tools/generate.py: the spec's examples for room_upgrades, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.room_upgrades;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(upgrade_room, response_0) {
  const auto got = loom::read<loom::cs::upgrade_room>(200, R"__json({"replacement_room":"!newroom:example.org"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
