// Generated by tools/generate.py: the spec's examples for space_hierarchy, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.space_hierarchy;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_space_hierarchy, response_0) {
  const auto got = loom::read<loom::cs::get_space_hierarchy>(200, R"__json({"rooms":[{"room_id":"!space:example.org","avatar_url":"mxc://example.org/abcdef","guest_can_join":false,"name":"The First Space","topic":"No other spaces were created first, ever","world_readable":true,"join_rule":"public","room_type":"m.space","num_joined_members":42,"canonical_alias":"#general:example.org","children_state":[{"type":"m.space.child","state_key":"!a:example.org","content":{"via":["example.org"]},"sender":"@alice:example.org","origin_server_ts":1629413349153}]}],"next_batch":"next_batch_token"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
