// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for support, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.support;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_wellknown_support, response_0) {
  const auto got = loom::read<loom::cs::get_wellknown_support>(200, R"__json({"contacts":[{"matrix_id":"@admin:example.org","email_address":"admin@example.org","role":"m.role.admin"},{"email_address":"security@example.org","role":"m.role.security"}],"support_page":"https://example.org/support.html"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
