// Generated by tools/generate.py: the spec's examples for tags, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.tags;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_room_tags, response_0) {
  const auto got = loom::read<loom::cs::get_room_tags>(200, R"__json({"tags":{"m.favourite":{"order":0.1},"u.Work":{"order":0.7},"u.Customers":{}}})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(set_room_tag, response_0) {
  const auto got = loom::read<loom::cs::set_room_tag>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}

CONSTEXPR_TEST(delete_room_tag, response_0) {
  const auto got = loom::read<loom::cs::delete_room_tag>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
