// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for threads_list, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.threads_list;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_thread_roots, response_0) {
  const auto got = loom::read<loom::cs::get_thread_roots>(200, R"__json({"chunk":[{"content":{"body":"This is an example text message","msgtype":"m.text","format":"org.matrix.custom.html","formatted_body":"<b>This is an example text message</b>"},"type":"m.room.message","event_id":"$143273582443PhrSn:example.org","room_id":"!jEsUZKDJdhlrceRyVU:example.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}}],"next_batch":"next_batch_token"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
