// Generated by tools/generate.py: the spec's examples for to_device, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.to_device;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(send_to_device, response_0) {
  const auto got = loom::read<loom::cs::send_to_device>(200, R"__json({})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
