// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for versions, read into their types.
import std;
import splice;
import knot;
import loom.api;
import loom.cs.versions;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_versions, response_0) {
  const auto got = loom::read<loom::cs::get_versions>(200, R"__json({"versions":["r0.0.1","v1.1"],"unstable_features":{"org.example.my_feature":true}})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
