// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for voip, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.voip;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_turn_server, response_0) {
  const auto got = loom::read<loom::cs::get_turn_server>(200, R"__json({"username":"1443779631:@user:example.com","password":"JlKfBy1QwLrO20385QyAtEyIv0=","uris":["turn:turn.example.com:3478?transport=udp","turn:10.20.30.40:3478?transport=tcp","turns:10.20.30.40:443?transport=tcp"],"ttl":86400})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
