// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate.py: the spec's examples for whoami, read into their types.
import std;
import knot;
import loom.api;
import loom.cs.whoami;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(get_token_owner, response_0) {
  const auto got = loom::read<loom::cs::get_token_owner>(200, R"__json({"user_id":"@joe:example.org","device_id":"ABC1234"})__json");
  if !consteval {
    if (!got) std::println("{}: {}", got.error().errcode, got.error().message);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
