// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_accepted_terms) {
  const auto got = knot::try_read<loom::ev::account_data_event>(R"__json({"content":{"accepted":["https://example.org/somewhere/terms-1.2-en.html","https://example.org/somewhere/privacy-1.2-en.html"]},"type":"m.accepted_terms"})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_accepted_terms_content_t>());
}
