// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_call_select_answer) {
  const auto got = knot::try_read<loom::ev::timeline_event>(R"__json({"content":{"version":"1","call_id":"12345","party_id":"67890","selected_party_id":"111213"},"type":"m.call.select_answer","event_id":"$143273582443PhrSn:example.org","room_id":"!jEsUZKDJdhlrceRyVU:example.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_call_select_answer_content_t>());
}
