// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_call_negotiate) {
  const auto got = knot::try_read<loom::ev::timeline_event>(R"__json({"content":{"version":"1","party_id":"67890","call_id":"12345","lifetime":10000,"description":{"type":"offer","sdp":"v=0\r\no=- 6584580628695956864 2 IN IP4 127.0.0.1[...]"},"sdp_stream_metadata":{"271828182845":{"purpose":"m.screenshare"},"314159265358":{"purpose":"m.usermedia"}}},"type":"m.call.negotiate","event_id":"$143273582443PhrSn:example.org","room_id":"!jEsUZKDJdhlrceRyVU:example.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_call_negotiate_content_t>());
}
