// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_forwarded_room_key) {
  const auto got = knot::try_read<loom::ev::account_data_event>(R"__json({"content":{"algorithm":"m.megolm.v1.aes-sha2","room_id":"!Cuyf34gef24t:localhost","session_id":"X3lUlvLELLYxeTx4yOVu6UDpasGEVO0Jbu+QFnm0cKQ","session_key":"AgAAAADxKHa9uFxcXzwYoNueL5Xqi69IkD4sni8Llf...","sender_key":"RF3s+E7RkTQTGF2d8Deol0FkQvgII2aJDf3/Jp5mxVU","sender_claimed_ed25519_key":"aj40p+aw64yPIdsxoog8jhPu9i7l7NcFRecuOQblE3Y","forwarding_curve25519_key_chain":["hPQNcabIABgGnx3/ACv/jmMmiQHoeFfuLB17tzWp6Hw"]},"type":"m.forwarded_room_key"})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_forwarded_room_key_content_t>());
}
