// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_ignored_user_list) {
  const auto got = knot::try_read<loom::ev::account_data_event>(R"__json({"content":{"ignored_users":{"@someone:example.org":{}}},"type":"m.ignored_user_list"})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_ignored_user_list_content_t>());
}
