// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_key_verification_accept) {
  const auto got = knot::try_read<loom::ev::account_data_event>(R"__json({"type":"m.key.verification.accept","content":{"transaction_id":"S0meUniqueAndOpaqueString","method":"m.sas.v1","key_agreement_protocol":"curve25519","hash":"sha256","message_authentication_code":"hkdf-hmac-sha256.v2","short_authentication_string":["decimal","emoji"],"commitment":"fQpGIW1Snz+pwLZu6sTy2aHy/DYWWTspTJRPyNp0PKkymfIsNffysMl6ObMMFdIJhk6g6pwlIqZ54rxo8SLmAg"}})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_key_verification_accept_content_t>());
}
