// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_key_verification_cancel) {
  const auto got = knot::try_read<loom::ev::account_data_event>(R"__json({"type":"m.key.verification.cancel","content":{"transaction_id":"S0meUniqueAndOpaqueString","code":"m.user","reason":"User rejected the key verification request"}})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_key_verification_cancel_content_t>());
}
