// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import splice;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_key_verification_start_m_sas_v1) {
  const auto got = knot::try_read<loom::ev::m_key_verification_start_m_sas_v1_content_t>(R"__json({"from_device":"BobDevice1","transaction_id":"S0meUniqueAndOpaqueString","method":"m.sas.v1","key_agreement_protocols":["curve25519"],"hashes":["sha256"],"message_authentication_codes":["hkdf-hmac-sha256.v2","hkdf-hmac-sha256"],"short_authentication_string":["decimal","emoji"]})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
