// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import splice;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_presence) {
  const auto got = knot::try_read<loom::ev::account_data_event>(R"__json({"content":{"avatar_url":"mxc://localhost/wefuiwegh8742w","last_active_ago":2478593,"presence":"online","currently_active":false,"status_msg":"Making cupcakes"},"type":"m.presence","sender":"@example:localhost"})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_presence_content_t>());
}
