// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_message_m_server_notice) {
  const auto got = knot::try_read<loom::ev::m_room_message_m_server_notice_content_t>(R"__json({"body":"Human-readable message to explain the notice","msgtype":"m.server_notice","server_notice_type":"m.server_notice.usage_limit_reached","admin_contact":"mailto:server.admin@example.org","limit_type":"monthly_active_user"})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
