// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_message_m_video) {
  const auto got = knot::try_read<loom::ev::m_room_message_m_video_content_t>(R"__json({"body":"Gangnam Style","url":"mxc://example.org/a526eYUSFFxlgbQYZmo442","info":{"thumbnail_url":"mxc://example.org/FHyPlCeYUSFFxlgbQYZmoEoe","thumbnail_info":{"mimetype":"image/jpeg","size":46144,"w":300,"h":300},"w":480,"h":320,"duration":2140786,"size":1563685,"mimetype":"video/mp4"},"msgtype":"m.video"})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
