// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_message_m_audio) {
  const auto got = knot::try_read<loom::ev::m_room_message_m_audio_content_t>(R"__json({"body":"Bee Gees - Stayin' Alive","url":"mxc://example.org/ffed755USFFxlgbQYZGtryd","info":{"duration":2140786,"size":1563685,"mimetype":"audio/mpeg"},"msgtype":"m.audio"})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
