// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_message_m_text) {
  const auto got = knot::try_read<loom::ev::m_room_message_m_text_content_t>(R"__json({"body":"This is an example text message","msgtype":"m.text","format":"org.matrix.custom.html","formatted_body":"<b>This is an example text message</b>"})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
