// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_message_m_location) {
  const auto got = knot::try_read<loom::ev::m_room_message_m_location_content_t>(R"__json({"body":"Big Ben, London, UK","geo_uri":"geo:51.5008,0.1247","info":{"thumbnail_url":"mxc://example.org/FHyPlCeYUSFFxlgbQYZmoEoe","thumbnail_info":{"mimetype":"image/jpeg","size":46144,"w":300,"h":300}},"msgtype":"m.location"})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
