// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import splice;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_message_m_file) {
  const auto got = knot::try_read<loom::ev::m_room_message_m_file_content_t>(R"__json({"body":"something-important.doc","filename":"something-important.doc","info":{"mimetype":"application/msword","size":46144},"msgtype":"m.file","url":"mxc://example.org/FHyPlCeYUSFFxlgbQYZmoEoe"})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
