// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import splice;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_key_withheld) {
  const auto got = knot::try_read<loom::ev::account_data_event>(R"__json({"content":{"algorithm":"m.megolm.v1.aes-sha2","room_id":"!Cuyf34gef24t:localhost","session_id":"X3lUlvLELLYxeTx4yOVu6UDpasGEVO0Jbu+QFnm0cKQ","sender_key":"RF3s+E7RkTQTGF2d8Deol0FkQvgII2aJDf3/Jp5mxVU","code":"m.unverified","reason":"Device not verified"},"type":"m.room_key.withheld"})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_room_key_withheld_content_t>());
}
