// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_key_bundle) {
  const auto got = knot::try_read<loom::ev::account_data_event>(R"__json({"type":"m.room_key_bundle","content":{"room_id":"!Cuyf34gef24t:localhost","file":{"v":"v2","url":"mxc://example.org/FHyPlCeYUSFFxlgbQYZmoEoe","key":{"alg":"A256CTR","ext":true,"k":"aWF6-32KGYaC3A_FEUCk1Bt0JA37zP0wrStgmdCaW-0","key_ops":["encrypt","decrypt"],"kty":"oct"},"iv":"w+sE15fzSc0AAAAAAAAAAA","hashes":{"sha256":"fdSLu/YkRx3Wyh3KQabP3rd6+SFiKg5lsJZQHtkSAYA"}}}})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_room_key_bundle_content_t>());
}
