// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import splice;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_image_pack) {
  const auto got = knot::try_read<loom::ev::state_event>(R"__json({"content":{"images":{"cat_wave":{"url":"mxc://example.org/abc123","body":"a waving cat","info":{"mimetype":"image/png","w":512,"h":512,"size":84400}},"cat_nap":{"url":"mxc://example.org/def456","body":"a sleeping cat"}},"pack":{"display_name":"Cats","avatar_url":"mxc://example.org/abc123","usage":["emoticon"],"attribution":"drawn by @alice:example.org"}},"type":"m.room.image_pack","event_id":"$143273582443PhrSn:example.org","room_id":"!jEsUZKDJdhlrceRyVU:example.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"},"state_key":""})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_room_image_pack_content_t>());
}
