// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_message_m_emote) {
  const auto got = knot::try_read<loom::ev::m_room_message_m_emote_content_t>(R"__json({"body":"thinks this is an example emote","msgtype":"m.emote","format":"org.matrix.custom.html","formatted_body":"thinks <b>this</b> is an example emote"})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
