// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_message_m_key_verification_request) {
  const auto got = knot::try_read<loom::ev::m_room_message_m_key_verification_request_content_t>(R"__json({"body":"Alice is requesting to verify your device, but your client does not support verification, so you may need to use a different verification method.","from_device":"AliceDevice2","methods":["m.sas.v1"],"to":"@bob:example.org","msgtype":"m.key.verification.request"})__json");
  CONSTEXPR_EXPECT_TRUE(got.has_value());
}
