// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_room_canonical_alias) {
  const auto got = knot::try_read<loom::ev::state_event>(R"__json({"content":{"alias":"#somewhere:localhost","alt_aliases":["#somewhere:example.org","#myroom:example.com"]},"type":"m.room.canonical_alias","event_id":"$143273582443PhrSn:example.org","room_id":"!jEsUZKDJdhlrceRyVU:example.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"},"state_key":""})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_room_canonical_alias_content_t>());
}
