// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate_events.py: the spec's example of each event, read into its type.
import std;
import knot;
import loom.ev;
import gtest;

#include "gtest/gtest-macros.h"
#include "../constexpr_test.h"

CONSTEXPR_TEST(events, m_sticker) {
  const auto got = knot::try_read<loom::ev::timeline_event>(R"__json({"content":{"body":"Landing","info":{"mimetype":"image/png","thumbnail_info":{"mimetype":"image/png","h":200,"w":140,"size":73602,"is_animated":true},"h":200,"thumbnail_url":"mxc://matrix.org/sHhqkFCvSkFwtmvtETOtKnLP","w":140,"size":73602},"url":"mxc://matrix.org/sHhqkFCvSkFwtmvtETOtKnLP"},"type":"m.sticker","event_id":"$143273582443PhrSn:example.org","room_id":"!jEsUZKDJdhlrceRyVU:example.org","sender":"@example:example.org","origin_server_ts":1432735824653,"unsigned":{"age":1234,"membership":"join"}})__json");
  if !consteval {
    if (!got) std::println("{} at {}", got.error().message, got.error().offset);
  }
  CONSTEXPR_EXPECT_TRUE(got.has_value());
  if (got)
    CONSTEXPR_EXPECT_TRUE(got->content.template is<loom::ev::m_sticker_content_t>());
}
